// Single source of page dates: src/data/page-dates.json (generated by scripts/page-dates.mjs).
import dates from '../data/page-dates.json';

const table = dates as Record<string, { published: string; modified: string }>;

export function getPageDates(canonicalPath: string): { published: string; modified: string } {
  const d = table[canonicalPath];
  if (!d) throw new Error(`page-dates.json has no entry for ${canonicalPath} - run scripts/page-dates.mjs`);
  return d;
}

/** "23 May 2026" (day=true) or "May 2026" */
export function formatDate(iso: string, day = false): string {
  return new Date(iso).toLocaleDateString('en-GB', {
    ...(day ? { day: 'numeric' } : {}), month: 'long', year: 'numeric', timeZone: 'Asia/Kolkata',
  });
}
