/**
 * Handlers: GET /admin/attempts/:attemptId (page-load claim) and
 *           POST /admin/attempts/:attemptId/release
 *
 * Phase 2 G2.A Session 1.b — service-layer handlers (no Fastify req/reply).
 *
 * Decision references:
 *   D3 — Claim transitions attempts.status from 'submitted' →
 *        'pending_admin_grading' (idempotent). No grading_jobs in Phase 1.
 *   D8 — Release transitions 'graded' → 'released'. This is the admin
 *        confirming the candidate can see results. Triggers result-released
 *        notification via module 13 (attempted safely, never blocks on failure).
 *
 * Cross-module SQL note:
 *   @assessiq/attempt-engine is NOT in this package's deps. Inline SQL via
 *   withTenant() — RLS on attempts, attempt_answers, attempt_questions,
 *   question_versions, gradings all enforce tenant isolation.
 *
 * Release (SP2, 2026-10-01):
 *   handleAdminReleaseAttempt delegates to module 09 releaseAttemptInTx (shared
 *   with bulk release and the worker auto-release sweep) and then sends the
 *   result email via module 13 — both static imports now.
 */

import { AppError, streamLogger, displayCandidate } from "@assessiq/core";
import { withTenant } from "@assessiq/tenancy";
import { auditInTx } from "@assessiq/audit-log";
import { releaseAttemptInTx } from "@assessiq/scoring";
import { sendResultReleasedEmail } from "@assessiq/notifications";
import { findGradingsForAttempt } from "../repository.js";
import { AI_GRADING_ERROR_CODES } from "../types.js";
import type { GradingsRow } from "../types.js";
import type { PoolClient } from "pg";

const log = streamLogger("grading");

// ---------------------------------------------------------------------------
// Local type aliases to avoid @assessiq/attempt-engine dep
// ---------------------------------------------------------------------------

// Re-export compatible shapes using local definitions
export interface AttemptAnswerRow {
  attempt_id: string;
  question_id: string;
  answer: unknown | null;
  flagged: boolean;
  time_spent_seconds: number;
  edits_count: number;
  client_revision: number;
  saved_at: Date | null;
}

export interface FrozenQuestionRow {
  question_id: string;
  position: number;
  question_version: number;
  type: string;
  topic: string;
  points: number;
  content: unknown;
  /**
   * Rubric snapshot at the question_version pinned by attempt-start.
   *
   * Exposed 2026-05-29 (review-UX): the admin attempt-detail page renders
   * anchor weights + concept words on the per-question grading cards so
   * the admin can verify "what was evaluated and why this score" before
   * Release-to-candidate. Previously excluded from this loader (comment
   * read "rubric column intentionally excluded — this read is for
   * display") but the loader IS the display read for admin grading
   * review, so the exclusion was over-conservative. Admin GET endpoint
   * is `adminOnly`-gated; candidates never see this row.
   *
   * NULL when the question has no authored rubric (synthesised rubrics
   * are ephemeral, generated by `handleAdminGrade` at grade-time, never
   * persisted, so won't appear here). Shape matches `RubricSchema` from
   * `@assessiq/rubric-engine` but kept `unknown` to avoid pulling that
   * type into the handler surface — FE narrows it.
   */
  rubric: unknown | null;
}

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface HandleAdminClaimAttemptOutput {
  attempt: {
    id: string;
    status: string;
    candidate_email: string | null;
    candidate_name: string;
    isErased: boolean;
    assessment_name: string;
    level_label: string;
    started_at: string | null;
    submitted_at: string | null;
  };
  answers: AttemptAnswerRow[];
  frozen_questions: FrozenQuestionRow[];
  gradings: GradingsRow[];
  /**
   * Phase 2 cache (Bug A robustness, 2026-05-29): the most-recent batch of
   * `GradingProposal[]` written by handleAdminGrade. Lets the FE hydrate
   * its proposals state on page load even if the original POST /grade
   * response was lost to a CF/proxy timeout. NOT committed grades — these
   * are review-state artifacts that still require admin Accept click
   * before any gradings row is written. Null when no grading has run or
   * after a successful gate-flip accept.
   *
   * Shape matches the runtime's `GradingProposal` shape exactly. Type left
   * `unknown` here to avoid pulling the runtime types into the handler
   * surface; the FE narrows it via the shared GradingProposal type from
   * `@assessiq/admin-api-types` (or equivalent).
   */
  ai_proposals: unknown[] | null;
  /**
   * Phase 2 cache: ISO-8601 timestamp set when handleAdminGrade started a
   * batch, nulled when the batch finishes (success or error path). Drives
   * the FE "Grading in progress" banner + 15s auto-poll cadence. Null
   * when no grading is running.
   */
  grading_started_at: string | null;
}

export interface HandleAdminReleaseAttemptOutput {
  attempt: { id: string; status: "released" };
}

// ---------------------------------------------------------------------------
// Helpers — inline SQL loaders
// ---------------------------------------------------------------------------

async function loadAnswers(
  client: PoolClient,
  attemptId: string,
): Promise<AttemptAnswerRow[]> {
  const result = await client.query<AttemptAnswerRow>(
    `SELECT attempt_id, question_id, answer, flagged,
            time_spent_seconds, edits_count, client_revision, saved_at
     FROM attempt_answers
     WHERE attempt_id = $1
     ORDER BY question_id ASC`,
    [attemptId],
  );
  return result.rows;
}

async function loadFrozenQuestions(
  client: PoolClient,
  attemptId: string,
): Promise<FrozenQuestionRow[]> {
  // 2026-05-29: rubric column NOW included so the admin review UI can
  // render anchor concepts + weights on per-question grading cards
  // (anchor chip enrichment + concept-coverage view). The previous "for
  // display only — rubric is served only by the grading code path" was
  // over-conservative — this loader IS the display read for the admin
  // grading review surface, and the GET endpoint is `adminOnly`-gated.
  // Candidates never reach this code path.
  const result = await client.query<FrozenQuestionRow>(
    `SELECT
       aq.question_id,
       aq.position,
       aq.question_version,
       q.type,
       q.topic,
       q.points,
       qv.content,
       qv.rubric
     FROM attempt_questions aq
     JOIN questions q ON q.id = aq.question_id
     JOIN question_versions qv
       ON qv.question_id = aq.question_id
      AND qv.version    = aq.question_version
     WHERE aq.attempt_id = $1
     ORDER BY aq.position ASC, aq.question_id ASC`,
    [attemptId],
  );
  return result.rows;
}

// ---------------------------------------------------------------------------
// Handlers
// ---------------------------------------------------------------------------

/**
 * Page-load handler for /admin/attempts/:id.
 *
 * Idempotently transitions attempts.status from 'submitted' to
 * 'pending_admin_grading', then loads answers + frozen_questions + gradings.
 * Second call (status already 'pending_admin_grading') is a no-op on the
 * UPDATE, but still returns the full page data.
 */
export async function handleAdminClaimAttempt(input: {
  tenantId: string;
  userId: string;
  attemptId: string;
}): Promise<HandleAdminClaimAttemptOutput> {
  const { tenantId, userId, attemptId } = input;

  return withTenant(tenantId, async (client) => {
    // Idempotent claim: transitions 'submitted' → 'pending_admin_grading'.
    // No-op when already 'pending_admin_grading' (rowCount = 0 is fine).
    const claimResult = await client.query(
      `UPDATE attempts
       SET status = 'pending_admin_grading'
       WHERE id = $1 AND status = 'submitted'`,
      [attemptId],
    );
    const wasClaimed = (claimResult.rowCount ?? 0) > 0;

    // Read current status + Phase 2 cache fields + candidate identity.
    // Phase 2 cache (2026-05-29 Bug A robustness): `ai_proposals` carries
    // the latest GradingProposal[] from handleAdminGrade (or null if no
    // grading run / cleared after gate-flip accept). `grading_started_at`
    // is the in-flight marker. Both feed the FE's hydration + banner +
    // 15s auto-poll logic so a Grade-all whose response was lost to a
    // CF/proxy timeout can still be picked up by the admin on return.
    // DPDP (2026-05-30): LEFT JOIN users/assessments/levels here so that
    // candidate identity is returned alongside attempt status in one query.
    // erased_at is included so displayCandidate() can substitute.
    const statusResult = await client.query<{
      status: string;
      ai_proposals: unknown[] | null;
      grading_started_at: Date | null;
      candidate_email: string | null;
      candidate_name: string | null;
      erased_at: string | null;
      assessment_name: string | null;
      level_label: string | null;
      started_at: Date | null;
      submitted_at: Date | null;
    }>(
      `SELECT
         a.status,
         a.ai_proposals,
         a.grading_started_at,
         u.email       AS candidate_email,
         u.name        AS candidate_name,
         u.erased_at,
         asm.name      AS assessment_name,
         lvl.label     AS level_label,
         a.started_at,
         a.submitted_at
       FROM attempts a
       LEFT JOIN users       u   ON u.id   = a.user_id
       LEFT JOIN assessments asm ON asm.id = a.assessment_id
       LEFT JOIN levels      lvl ON lvl.id = asm.level_id
       WHERE a.id = $1
       LIMIT 1`,
      [attemptId],
    );
    const statusRow = statusResult.rows[0];
    if (statusRow === undefined) {
      throw new AppError(
        `Attempt ${attemptId} not found`,
        AI_GRADING_ERROR_CODES.ATTEMPT_NOT_FOUND,
        404,
      );
    }

    // Apply displayCandidate substitution for DPDP erasure
    const candidateDisplay = displayCandidate({
      id: attemptId,
      name: statusRow.candidate_name,
      email: statusRow.candidate_email,
      erased_at: statusRow.erased_at,
    });

    // G3.D audit: only on the actual transition. Re-claim of an already-claimed
    // attempt produces no audit row, matching the idempotent UPDATE semantic.
    if (wasClaimed) {
      await auditInTx(client, {
        action: "grading.claimed",
        actorKind: "user",
        actorUserId: userId,
        tenantId,
        entityType: "attempt",
        entityId: attemptId,
        before: { attempt_status: "submitted" },
        after: { attempt_status: "pending_admin_grading" },
      });
    }

    const [answers, frozen_questions, gradings] = await Promise.all([
      loadAnswers(client, attemptId),
      loadFrozenQuestions(client, attemptId),
      findGradingsForAttempt(client, attemptId),
    ]);

    return {
      attempt: {
        id: attemptId,
        status: statusRow.status,
        candidate_email: candidateDisplay.email,
        candidate_name: candidateDisplay.name,
        isErased: candidateDisplay.isErased,
        assessment_name: statusRow.assessment_name ?? '(unknown)',
        level_label: statusRow.level_label ?? '(unknown)',
        started_at: statusRow.started_at?.toISOString() ?? null,
        submitted_at: statusRow.submitted_at?.toISOString() ?? null,
      },
      answers,
      frozen_questions,
      gradings,
      ai_proposals: statusRow.ai_proposals,
      grading_started_at:
        statusRow.grading_started_at !== null
          ? statusRow.grading_started_at.toISOString()
          : null,
    };
  });
}

/**
 * Release handler: transitions 'graded' → 'released' (publish to the candidate).
 *
 * SP2 (2026-10-01): the release itself lives in module 09 releaseAttemptInTx —
 * one shared core for this manual click, the bulk "release all ready" and the
 * worker auto-release sweep. It enforces the erasure gate (422), requires a
 * COMPLETE result (status 'graded' + evaluation released to the tenant, else 409
 * RESULT_NOT_READY), writes the grading.released audit row, and issues the
 * certificate inside a SAVEPOINT (a certificate failure never undoes the
 * release). The static imports at the top of this file replace the old
 * Function-constructor dynamic imports, which also hid the fact that
 * sendResultReleasedEmail never existed.
 *
 * The result email is sent AFTER the release transaction commits and is
 * best-effort (sendResultReleasedEmail never throws; failures are only logged).
 */
export async function handleAdminReleaseAttempt(input: {
  tenantId: string;
  userId: string;
  attemptId: string;
}): Promise<HandleAdminReleaseAttemptOutput> {
  const { tenantId, userId, attemptId } = input;

  await withTenant(tenantId, (client) =>
    releaseAttemptInTx(client, {
      tenantId,
      attemptId,
      actor: { kind: "user", userId },
    }),
  );

  await sendReleaseEmailSafely(tenantId, attemptId);

  log.info({ attemptId }, "grading.release.complete");

  return { attempt: { id: attemptId, status: "released" } };
}

/**
 * Post-commit, best-effort result email. sendResultReleasedEmail already never
 * throws; the extra guard keeps an unexpected failure from turning a successful,
 * committed release into an error response.
 */
export async function sendReleaseEmailSafely(
  tenantId: string,
  attemptId: string,
): Promise<void> {
  try {
    await sendResultReleasedEmail({ tenantId, attemptId });
  } catch (err) {
    log.warn({ attemptId, error: String(err) }, "grading.release.notification_failed");
  }
}
