/**
 * Handlers: GET /admin/attempts/:attemptId (attempt review payload) and
 *           POST /admin/attempts/:attemptId/release
 *
 * Phase 2 G2.A Session 1.b — service-layer handlers (no Fastify req/reply).
 *
 * Decision references:
 *   D8 — Release transitions 'graded' → 'released'. This is the admin
 *        confirming the candidate can see results. Triggers result-released
 *        notification via module 13 (attempted safely, never blocks on failure).
 *
 * Cross-module SQL note:
 *   @assessiq/attempt-engine is NOT in this package's deps. Inline SQL via
 *   withTenant() — RLS on attempts, attempt_answers, attempt_questions,
 *   question_versions, gradings all enforce tenant isolation.
 *
 * Release (SP2, 2026-10-01):
 *   handleAdminReleaseAttempt delegates to module 09 releaseAttemptInTx (shared
 *   with bulk release and the worker auto-release sweep) and then sends the
 *   result email via module 13 — both static imports now.
 *
 * Phase II (2026-10-01) — platform evaluation queue:
 *   The GET is now READ-ONLY. It used to claim the attempt (submitted →
 *   pending_admin_grading) and write a grading.claimed audit row on every first
 *   open — a side effect on a GET, and meaningless now that tenants no longer
 *   grade. (The catalog action name stays for historical rows.) The payload is
 *   built by loadAttemptReview(), shared with the platform evaluator's view
 *   (handlers/super-evaluations.ts) with a per-audience projection:
 *     - 'tenant'   : candidate identity included (the tenant's own data); while
 *                    the evaluation is still with AssessIQ (awaiting_evaluation)
 *                    gradings / score / ai_proposals are HIDDEN; ai_proposals is
 *                    always null for tenants (AI review state is platform-only).
 *     - 'platform' : NO candidate name / email / erasure flag (blind evaluation);
 *                    everything the evaluator needs, plus tenant + evaluation meta.
 */

import { AppError, streamLogger, displayCandidate } from "@assessiq/core";
import { withTenant } from "@assessiq/tenancy";
import { releaseAttemptInTx } from "@assessiq/scoring";
import { sendResultReleasedEmail } from "@assessiq/notifications";
import { deriveEvaluationStatus, findGradingsForAttempt } from "../repository.js";
import type { EvaluationStatus } from "../repository.js";
import { AI_GRADING_ERROR_CODES } from "../types.js";
import type { GradingsRow } from "../types.js";
import type { PoolClient } from "pg";

const log = streamLogger("grading");

// ---------------------------------------------------------------------------
// Local type aliases to avoid @assessiq/attempt-engine dep
// ---------------------------------------------------------------------------

// Re-export compatible shapes using local definitions
export interface AttemptAnswerRow {
  attempt_id: string;
  question_id: string;
  answer: unknown | null;
  flagged: boolean;
  time_spent_seconds: number;
  edits_count: number;
  client_revision: number;
  saved_at: Date | null;
}

export interface FrozenQuestionRow {
  question_id: string;
  position: number;
  question_version: number;
  type: string;
  topic: string;
  points: number;
  content: unknown;
  /**
   * Rubric snapshot at the question_version pinned by attempt-start.
   *
   * Exposed 2026-05-29 (review-UX): the admin attempt-detail page renders
   * anchor weights + concept words on the per-question grading cards so
   * the admin can verify "what was evaluated and why this score" before
   * Release-to-candidate. Previously excluded from this loader (comment
   * read "rubric column intentionally excluded — this read is for
   * display") but the loader IS the display read for admin grading
   * review, so the exclusion was over-conservative. Admin GET endpoint
   * is `adminOnly`-gated; candidates never see this row.
   *
   * NULL when the question has no authored rubric (synthesised rubrics
   * are ephemeral, generated by `handleAdminGrade` at grade-time, never
   * persisted, so won't appear here). Shape matches `RubricSchema` from
   * `@assessiq/rubric-engine` but kept `unknown` to avoid pulling that
   * type into the handler surface — FE narrows it.
   */
  rubric: unknown | null;
}

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/** attempt_scores summary shown next to the grades (the visible subset of 09 AttemptScore). */
export interface AttemptScoreSummary {
  total_earned: number;
  total_max: number;
  auto_pct: number;
  pending_review: boolean;
}

export interface HandleAdminClaimAttemptOutput {
  attempt: {
    id: string;
    status: string;
    candidate_email: string | null;
    candidate_name: string;
    isErased: boolean;
    assessment_name: string;
    level_label: string;
    started_at: string | null;
    submitted_at: string | null;
  };
  answers: AttemptAnswerRow[];
  frozen_questions: FrozenQuestionRow[];
  /** Phase II: [] while the evaluation is still with AssessIQ (awaiting_evaluation). */
  gradings: GradingsRow[];
  /**
   * Phase II: ALWAYS null for tenant roles. The AI review cache (the latest
   * `GradingProposal[]` from handleAdminGrade, Bug A robustness 2026-05-29) is
   * platform-evaluator state — it is only served by the platform evaluation view
   * (handlers/super-evaluations.ts). Tenants no longer run or accept AI grading.
   */
  ai_proposals: unknown[] | null;
  /**
   * Phase II: ALWAYS null for tenant roles (the in-flight AI marker is platform
   * state; see ai_proposals).
   */
  grading_started_at: string | null;
  /** Phase II: tenant-facing evaluation state (repository.deriveEvaluationStatus). */
  evaluation_status: EvaluationStatus;
  /** ISO timestamp the platform released the evaluation to the tenant; null until then. */
  evaluation_released_at: string | null;
  /** The tenant's own "send back" note (null when the attempt was never sent back). */
  evaluation_note: string | null;
  evaluation_sent_back_at: string | null;
  /** attempt_scores summary; null while awaiting_evaluation (provisional totals are never shown). */
  score: AttemptScoreSummary | null;
}

export interface HandleAdminReleaseAttemptOutput {
  attempt: { id: string; status: "released" };
}

// ---------------------------------------------------------------------------
// Helpers — inline SQL loaders
// ---------------------------------------------------------------------------

async function loadAnswers(
  client: PoolClient,
  attemptId: string,
): Promise<AttemptAnswerRow[]> {
  const result = await client.query<AttemptAnswerRow>(
    `SELECT attempt_id, question_id, answer, flagged,
            time_spent_seconds, edits_count, client_revision, saved_at
     FROM attempt_answers
     WHERE attempt_id = $1
     ORDER BY question_id ASC`,
    [attemptId],
  );
  return result.rows;
}

async function loadFrozenQuestions(
  client: PoolClient,
  attemptId: string,
): Promise<FrozenQuestionRow[]> {
  // 2026-05-29: rubric column NOW included so the admin review UI can
  // render anchor concepts + weights on per-question grading cards
  // (anchor chip enrichment + concept-coverage view). The previous "for
  // display only — rubric is served only by the grading code path" was
  // over-conservative — this loader IS the display read for the admin
  // grading review surface, and the GET endpoint is `adminOnly`-gated.
  // Candidates never reach this code path.
  const result = await client.query<FrozenQuestionRow>(
    `SELECT
       aq.question_id,
       aq.position,
       aq.question_version,
       q.type,
       q.topic,
       q.points,
       qv.content,
       qv.rubric
     FROM attempt_questions aq
     JOIN questions q ON q.id = aq.question_id
     JOIN question_versions qv
       ON qv.question_id = aq.question_id
      AND qv.version    = aq.question_version
     WHERE aq.attempt_id = $1
     ORDER BY aq.position ASC, aq.question_id ASC`,
    [attemptId],
  );
  return result.rows;
}

// ---------------------------------------------------------------------------
// Handlers
// ---------------------------------------------------------------------------

/** attempt_scores totals for the review payload; null when no rollup row exists yet. */
async function loadScoreSummary(
  client: PoolClient,
  attemptId: string,
): Promise<AttemptScoreSummary | null> {
  const res = await client.query<AttemptScoreSummary>(
    `SELECT total_earned::float8 AS total_earned,
            total_max::float8    AS total_max,
            auto_pct::float8     AS auto_pct,
            pending_review
       FROM attempt_scores
      WHERE attempt_id = $1`,
    [attemptId],
  );
  return res.rows[0] ?? null;
}

/** Raw attempt row behind the review payload (identity columns are NULL for the platform audience). */
export interface AttemptReviewRow {
  status: string;
  ai_proposals: unknown[] | null;
  grading_started_at: Date | null;
  evaluation_released_at: Date | null;
  evaluation_note: string | null;
  evaluation_sent_back_at: Date | null;
  candidate_email: string | null;
  candidate_name: string | null;
  erased_at: string | null;
  assessment_name: string | null;
  level_label: string | null;
  started_at: Date | null;
  submitted_at: Date | null;
  tenant_name: string | null;
}

export interface AttemptReview {
  row: AttemptReviewRow;
  evaluation_status: EvaluationStatus;
  answers: AttemptAnswerRow[];
  frozen_questions: FrozenQuestionRow[];
  gradings: GradingsRow[];
  score: AttemptScoreSummary | null;
}

/**
 * Read-only loader behind the attempt review payload (NO writes, no audit).
 * Must run inside withTenant(<the attempt's tenant>) — RLS scopes every read.
 *
 * `audience` decides what is projected (see the file header):
 *   'tenant'   joins users for the candidate identity (DPDP erasure is applied by
 *              the caller via displayCandidate) and HIDES gradings + score while the
 *              evaluation is still with AssessIQ — a tenant never sees AI grades or a
 *              provisional total before the platform releases the evaluation.
 *   'platform' never selects candidate columns at all (blind evaluation) and always
 *              returns gradings + score: the evaluator needs them.
 * Throws 404 AIG_ATTEMPT_NOT_FOUND when RLS hides the row or it does not exist.
 */
export async function loadAttemptReview(
  client: PoolClient,
  attemptId: string,
  audience: "tenant" | "platform",
): Promise<AttemptReview> {
  // Static SQL fragments (never user input).
  const identityCols =
    audience === "tenant"
      ? "u.email AS candidate_email, u.name AS candidate_name, u.erased_at"
      : "NULL::text AS candidate_email, NULL::text AS candidate_name, NULL::text AS erased_at";
  const identityJoin = audience === "tenant" ? "LEFT JOIN users u ON u.id = a.user_id" : "";

  // Phase 2 cache (2026-05-29 Bug A robustness): `ai_proposals` carries the latest
  // GradingProposal[] from handleAdminGrade (or null if no grading run / cleared
  // after the completing accept); `grading_started_at` is the in-flight marker.
  // Both feed the platform evaluator's hydration + banner + auto-poll so a
  // Grade-all whose response was lost to a CF/proxy timeout can be picked up again.
  const statusResult = await client.query<AttemptReviewRow>(
    `SELECT
       a.status,
       a.ai_proposals,
       a.grading_started_at,
       a.evaluation_released_at,
       a.evaluation_note,
       a.evaluation_sent_back_at,
       ${identityCols},
       asm.name      AS assessment_name,
       lvl.label     AS level_label,
       a.started_at,
       a.submitted_at,
       t.name        AS tenant_name
     FROM attempts a
     ${identityJoin}
     LEFT JOIN assessments asm ON asm.id = a.assessment_id
     LEFT JOIN levels      lvl ON lvl.id = asm.level_id
     LEFT JOIN tenants     t   ON t.id   = a.tenant_id
     WHERE a.id = $1
     LIMIT 1`,
    [attemptId],
  );
  const row = statusResult.rows[0];
  if (row === undefined) {
    throw new AppError(
      `Attempt ${attemptId} not found`,
      AI_GRADING_ERROR_CODES.ATTEMPT_NOT_FOUND,
      404,
    );
  }

  const evaluation_status = deriveEvaluationStatus(row.status, row.evaluation_released_at !== null);
  const hidden = audience === "tenant" && evaluation_status === "awaiting_evaluation";

  const [answers, frozen_questions, gradings, score] = await Promise.all([
    loadAnswers(client, attemptId),
    loadFrozenQuestions(client, attemptId),
    hidden ? Promise.resolve<GradingsRow[]>([]) : findGradingsForAttempt(client, attemptId),
    hidden ? Promise.resolve<AttemptScoreSummary | null>(null) : loadScoreSummary(client, attemptId),
  ]);

  return { row, evaluation_status, answers, frozen_questions, gradings, score };
}

/**
 * GET /admin/attempts/:id — the tenant's attempt review payload.
 *
 * READ-ONLY (Phase II): no claim transition, no audit row. The handler name is kept
 * for the route + callers; "claim" is historical. `userId` is accepted for signature
 * stability and is not used.
 */
export async function handleAdminClaimAttempt(input: {
  tenantId: string;
  userId: string;
  attemptId: string;
}): Promise<HandleAdminClaimAttemptOutput> {
  const { tenantId, attemptId } = input;

  return withTenant(tenantId, async (client) => {
    const r = await loadAttemptReview(client, attemptId, "tenant");
    const { row } = r;

    // Apply displayCandidate substitution for DPDP erasure
    const candidateDisplay = displayCandidate({
      id: attemptId,
      name: row.candidate_name,
      email: row.candidate_email,
      erased_at: row.erased_at,
    });

    return {
      attempt: {
        id: attemptId,
        status: row.status,
        candidate_email: candidateDisplay.email,
        candidate_name: candidateDisplay.name,
        isErased: candidateDisplay.isErased,
        assessment_name: row.assessment_name ?? '(unknown)',
        level_label: row.level_label ?? '(unknown)',
        started_at: row.started_at?.toISOString() ?? null,
        submitted_at: row.submitted_at?.toISOString() ?? null,
      },
      answers: r.answers,
      frozen_questions: r.frozen_questions,
      gradings: r.gradings,
      // AI review state is platform-only (see HandleAdminClaimAttemptOutput).
      ai_proposals: null,
      grading_started_at: null,
      evaluation_status: r.evaluation_status,
      evaluation_released_at: row.evaluation_released_at?.toISOString() ?? null,
      evaluation_note: row.evaluation_note,
      evaluation_sent_back_at: row.evaluation_sent_back_at?.toISOString() ?? null,
      score: r.score,
    };
  });
}

/**
 * Release handler: transitions 'graded' → 'released' (publish to the candidate).
 *
 * SP2 (2026-10-01): the release itself lives in module 09 releaseAttemptInTx —
 * one shared core for this manual click, the bulk "release all ready" and the
 * worker auto-release sweep. It enforces the erasure gate (422), requires a
 * COMPLETE result (status 'graded' + evaluation released to the tenant, else 409
 * RESULT_NOT_READY), writes the grading.released audit row, and issues the
 * certificate inside a SAVEPOINT (a certificate failure never undoes the
 * release). The static imports at the top of this file replace the old
 * Function-constructor dynamic imports, which also hid the fact that
 * sendResultReleasedEmail never existed.
 *
 * The result email is sent AFTER the release transaction commits and is
 * best-effort (sendResultReleasedEmail never throws; failures are only logged).
 */
export async function handleAdminReleaseAttempt(input: {
  tenantId: string;
  userId: string;
  attemptId: string;
}): Promise<HandleAdminReleaseAttemptOutput> {
  const { tenantId, userId, attemptId } = input;

  await withTenant(tenantId, (client) =>
    releaseAttemptInTx(client, {
      tenantId,
      attemptId,
      actor: { kind: "user", userId },
    }),
  );

  await sendReleaseEmailSafely(tenantId, attemptId);

  log.info({ attemptId }, "grading.release.complete");

  return { attempt: { id: attemptId, status: "released" } };
}

/**
 * Post-commit, best-effort result email. sendResultReleasedEmail already never
 * throws; the extra guard keeps an unexpected failure from turning a successful,
 * committed release into an error response.
 */
export async function sendReleaseEmailSafely(
  tenantId: string,
  attemptId: string,
): Promise<void> {
  try {
    await sendResultReleasedEmail({ tenantId, attemptId });
  } catch (err) {
    log.warn({ attemptId, error: String(err) }, "grading.release.notification_failed");
  }
}
