-- owned by modules/04-question-bank
-- 0109_seed_platform_aptitude_pack.sql
-- GENERATED by tools/gen-aptitude-migration.ts — do not hand-edit; regenerate and, if this
-- file was already applied anywhere, ship the change as a NEW migration (checksum drift gate).
-- Input sha256: 8e7f351e5c7eb5cce1edaad66839bf2302da5c7a26a4219275b5a9666e5dc9bc | questions: 60 | mode: published
--
-- WHAT: seeds the platform-library "Aptitude" domain (3 categories, MCQ only) and the
--   "Campus Placement Aptitude" pack with 60 MCQ questions into the PLATFORM tenant, and
--   registers the domain (+ categories) in every company tenant exactly like
--   platform-domains.ts createPlatformDomain (INSERT ... source='platform', ON CONFLICT DO NOTHING).
-- WHY in SQL: the content is static seed data; same sanctioned pattern as 0019/0083.
--   Tenants still need an entitlement (domain 'aptitude' or this pack) to use it.
-- MODE published: pack published v2, questions active v2 + question_versions v1 snapshot (publishPack end-state).
-- IDEMPOTENT: domains/categories ON CONFLICT DO NOTHING; pack guarded by slug; questions have
--   deterministic ids (md5 of the external id) + ON CONFLICT DO NOTHING. Re-run = no-op.
-- NO-OP (with NOTICE) when the platform tenant or a platform super_admin/admin user is absent
--   (fresh DB before the manual platform bootstrap) — re-apply with
--   'tools/migrate.ts --force-rerun 0109_seed_platform_aptitude_pack.sql' after bootstrap.

DO $aptmig$
DECLARE
  v_platform uuid;
  v_user     uuid;
  v_domain   uuid;
  v_pack     uuid;
  v_have     int;
BEGIN
  SELECT id INTO v_platform FROM tenants WHERE slug = 'platform' LIMIT 1;
  IF v_platform IS NULL THEN
    RAISE NOTICE '0109: platform tenant absent — skipping aptitude seed';
    RETURN;
  END IF;

  SELECT id INTO v_user FROM users
   WHERE tenant_id = v_platform AND role IN ('super_admin', 'admin')
     AND status = 'active' AND deleted_at IS NULL
   ORDER BY (role = 'super_admin') DESC, created_at ASC LIMIT 1;
  IF v_user IS NULL THEN
    RAISE NOTICE '0109: no active platform super_admin/admin user — skipping aptitude seed';
    RETURN;
  END IF;

  -- 1. Canonical platform domain (display_order = MAX+1 within the platform tenant).
  INSERT INTO domains (tenant_id, slug, name, description, source, status, display_order)
  SELECT v_platform, $aq$aptitude$aq$, 'Aptitude',
         'Campus-placement aptitude: quantitative, logical and verbal ability (MCQ).',
         'platform', 'active',
         COALESCE((SELECT MAX(display_order) FROM domains WHERE tenant_id = v_platform), 0) + 1
  ON CONFLICT (tenant_id, slug) DO NOTHING;

  -- 2. Propagate to every NON-platform tenant (same SQL as createPlatformDomain).
  INSERT INTO domains (tenant_id, slug, name, description, source, status, display_order)
  SELECT t.id, pd.slug, pd.name, pd.description, 'platform', 'active',
         COALESCE((SELECT MAX(d.display_order) FROM domains d WHERE d.tenant_id = t.id), 0) + 1
    FROM tenants t
    CROSS JOIN (SELECT slug, name, description FROM domains
                 WHERE tenant_id = v_platform AND slug = $aq$aptitude$aq$) pd
   WHERE t.id <> v_platform
  ON CONFLICT (tenant_id, slug) DO NOTHING;

  SELECT id INTO v_domain FROM domains WHERE tenant_id = v_platform AND slug = $aq$aptitude$aq$;

  -- 3. Categories (MCQ only) in the platform tenant AND every tenant holding a platform-origin
  --    copy of the domain (never under a tenant-LOCAL 'aptitude' domain — same guard as seed.ts).
  --    createPlatformDomain does not propagate categories; clone-on-use self-heals them, but we
  --    register them up front so the taxonomy is complete at once.
  INSERT INTO categories (tenant_id, domain_id, slug, name, relevance_score, default_selected,
                          supported_types, default_question_count, status)
  SELECT d.tenant_id, d.id, c.slug, c.name, c.score, true, '["mcq"]'::jsonb, 1, 'active'
    FROM domains d
    CROSS JOIN (VALUES
      ($aq$quantitative-aptitude$aq$, $aq$Quantitative Aptitude$aq$, 3),
      ($aq$logical-reasoning$aq$, $aq$Logical Reasoning$aq$, 2),
      ($aq$verbal-ability$aq$, $aq$Verbal Ability$aq$, 1)
    ) AS c(slug, name, score)
   WHERE d.slug = $aq$aptitude$aq$ AND d.source = 'platform'
  ON CONFLICT (tenant_id, domain_id, slug) DO NOTHING;

  -- 4. Pack (platform tenant). Skipped if a pack with this slug already exists.
  INSERT INTO question_packs (id, tenant_id, slug, name, domain, description, status, version, created_by)
  SELECT md5('assessiq:aptitude:pack')::uuid, v_platform, $aq$campus-placement-aptitude$aq$, $aq$Campus Placement Aptitude$aq$,
         $aq$aptitude$aq$, $aq$Quantitative aptitude, logical reasoning and verbal ability for campus placement screening.$aq$, 'published', 2, v_user
   WHERE NOT EXISTS (SELECT 1 FROM question_packs WHERE tenant_id = v_platform AND slug = $aq$campus-placement-aptitude$aq$);

  SELECT id INTO v_pack FROM question_packs
   WHERE tenant_id = v_platform AND slug = $aq$campus-placement-aptitude$aq$ ORDER BY version DESC LIMIT 1;

  -- 5. Levels (L1/L2 -> position 1/2; only levels that have questions).
  INSERT INTO levels (pack_id, position, label, description, duration_minutes, default_question_count, passing_score_pct)
  SELECT v_pack, l.position, l.label, l.description, l.duration, l.cnt, l.pass
    FROM (VALUES
      (1, 'L1', $aq$Foundation: core campus-placement aptitude.$aq$, 45, 30, 60),
      (2, 'L2', $aq$Advanced: multi-step aptitude problems.$aq$, 45, 30, 60)
    ) AS l(position, label, description, duration, cnt, pass)
  ON CONFLICT (pack_id, position) DO NOTHING;

  -- 6. Questions: 1 point each, MCQ content = {question, options, correct, rationale}
  --    (McqContentSchema, strict). Deterministic ids make re-runs no-ops.
  INSERT INTO questions (id, pack_id, level_id, type, topic, points, status, version, content,
                         created_by, domain_id, category_id)
  SELECT md5('assessiq:aptitude:' || v.ext_id)::uuid, v_pack, lv.id, 'mcq', v.topic, 1,
         'active', 2, v.content::jsonb, v_user, v_domain, c.id
    FROM (VALUES
      ($aq$APT-Q-001$aq$, 1, $aq$quantitative-aptitude$aq$, $aq$percentages$aq$, $aq${"question":"What is 35% of 240?","options":["72","96","84","78"],"correct":2,"rationale":"35% of 240 = 35 × 240 ÷ 100 = 8400 ÷ 100 = 84."}$aq$),
      ($aq$APT-Q-002$aq$, 1, $aq$quantitative-aptitude$aq$, $aq$profit & loss$aq$, $aq${"question":"A shopkeeper buys a bag for ₹800 and sells it at a profit of 15%. What is the selling price?","options":["₹920","₹815","₹950","₹880"],"correct":0,"rationale":"Profit = 15% of 800 = ₹120. SP = 800 + 120 = ₹920."}$aq$),
      ($aq$APT-Q-003$aq$, 1, $aq$quantitative-aptitude$aq$, $aq$simple & compound interest$aq$, $aq${"question":"What is the simple interest on ₹5000 at 6% per annum for 3 years?","options":["₹1800","₹300","₹5900","₹900"],"correct":3,"rationale":"SI = P × R × T ÷ 100 = 5000 × 6 × 3 ÷ 100 = ₹900."}$aq$),
      ($aq$APT-Q-004$aq$, 1, $aq$quantitative-aptitude$aq$, $aq$ratio & proportion$aq$, $aq${"question":"₹720 is divided between Asha and Bhavin in the ratio 5 : 4. What is Asha's share?","options":["₹360","₹400","₹450","₹320"],"correct":1,"rationale":"Total parts = 9; one part = 720 ÷ 9 = 80. Asha = 5 × 80 = ₹400."}$aq$),
      ($aq$APT-Q-005$aq$, 1, $aq$quantitative-aptitude$aq$, $aq$averages$aq$, $aq${"question":"The average of five numbers is 18. If the sum of four of them is 70, what is the fifth number?","options":["18","20","22","16"],"correct":1,"rationale":"Total = 5 × 18 = 90. Fifth = 90 − 70 = 20."}$aq$),
      ($aq$APT-Q-006$aq$, 1, $aq$quantitative-aptitude$aq$, $aq$time & work$aq$, $aq${"question":"A can finish a job in 12 days and B can finish it in 24 days. Working together, in how many days will they finish it?","options":["6 days","18 days","12 days","8 days"],"correct":3,"rationale":"Combined rate = 1/12 + 1/24 = 3/24 = 1/8 per day. So 8 days."}$aq$),
      ($aq$APT-Q-007$aq$, 1, $aq$quantitative-aptitude$aq$, $aq$time speed distance$aq$, $aq${"question":"A 120 m long train crosses a signal pole in 6 seconds. What is its speed?","options":["72 km/h","60 km/h","80 km/h","54 km/h"],"correct":0,"rationale":"Speed = 120 ÷ 6 = 20 m/s. In km/h: 20 × 18/5 = 72 km/h."}$aq$),
      ($aq$APT-Q-008$aq$, 1, $aq$quantitative-aptitude$aq$, $aq$number system$aq$, $aq${"question":"What is the LCM of 12, 15 and 20?","options":["120","30","60","180"],"correct":2,"rationale":"12 = 2²×3, 15 = 3×5, 20 = 2²×5. LCM = 2²×3×5 = 60."}$aq$),
      ($aq$APT-Q-009$aq$, 1, $aq$quantitative-aptitude$aq$, $aq$ages$aq$, $aq${"question":"A father is 3 times as old as his son. The sum of their ages is 48 years. What is the father's age?","options":["12 years","32 years","40 years","36 years"],"correct":3,"rationale":"Let son = x; father = 3x; 4x = 48, x = 12. Father = 36 years."}$aq$),
      ($aq$APT-Q-010$aq$, 1, $aq$quantitative-aptitude$aq$, $aq$simplification$aq$, $aq${"question":"Simplify: 15 + 12 × 3 − 18 ÷ 6","options":["78","48","45","51"],"correct":1,"rationale":"BODMAS: 12 × 3 = 36 and 18 ÷ 6 = 3. So 15 + 36 − 3 = 48."}$aq$),
      ($aq$APT-Q-011$aq$, 2, $aq$quantitative-aptitude$aq$, $aq$simple & compound interest$aq$, $aq${"question":"What is the compound interest on ₹8000 at 10% per annum for 2 years, compounded annually?","options":["₹1600","₹1700","₹1680","₹9680"],"correct":2,"rationale":"Amount = 8000 × 1.1 × 1.1 = 9680. CI = 9680 − 8000 = ₹1680."}$aq$),
      ($aq$APT-Q-012$aq$, 2, $aq$quantitative-aptitude$aq$, $aq$pipes & cisterns$aq$, $aq${"question":"Pipe A fills a tank in 12 hours and pipe B in 15 hours, while pipe C empties it in 20 hours. If all three are opened together, how long will the empty tank take to fill?","options":["10 hours","8 hours","12 hours","15 hours"],"correct":0,"rationale":"Net rate = 1/12 + 1/15 − 1/20 = (5 + 4 − 3)/60 = 6/60 = 1/10. Time = 10 hours."}$aq$),
      ($aq$APT-Q-013$aq$, 2, $aq$quantitative-aptitude$aq$, $aq$mixtures & alligation$aq$, $aq${"question":"In what ratio must milk costing ₹60 per litre be mixed with milk costing ₹80 per litre so that the mixture is worth ₹66 per litre?","options":["7 : 3","3 : 7","2 : 1","4 : 3"],"correct":0,"rationale":"Alligation: cheaper : dearer = (80 − 66) : (66 − 60) = 14 : 6 = 7 : 3."}$aq$),
      ($aq$APT-Q-014$aq$, 2, $aq$quantitative-aptitude$aq$, $aq$permutations & combinations$aq$, $aq${"question":"In how many distinct ways can the letters of the word LEVEL be arranged?","options":["60","120","30","15"],"correct":2,"rationale":"5 letters with L repeated twice and E repeated twice: 5! ÷ (2! × 2!) = 120 ÷ 4 = 30."}$aq$),
      ($aq$APT-Q-015$aq$, 2, $aq$quantitative-aptitude$aq$, $aq$probability$aq$, $aq${"question":"Two fair dice are thrown together. What is the probability that the sum of the numbers is 9?","options":["1/6","1/9","5/36","1/12"],"correct":1,"rationale":"Favourable: (3,6), (4,5), (5,4), (6,3) = 4 outcomes out of 36. Probability = 4/36 = 1/9."}$aq$),
      ($aq$APT-Q-016$aq$, 2, $aq$quantitative-aptitude$aq$, $aq$profit & loss$aq$, $aq${"question":"A trader marks an article 40% above its cost price and then allows a discount of 15%. What is his profit percentage?","options":["25%","21%","15%","19%"],"correct":3,"rationale":"Let CP = 100. MP = 140. SP = 140 × 0.85 = 119. Profit = 19%."}$aq$),
      ($aq$APT-Q-017$aq$, 2, $aq$quantitative-aptitude$aq$, $aq$time speed distance$aq$, $aq${"question":"A boat's speed in still water is 15 km/h and the stream flows at 3 km/h. How long does it take to go 36 km downstream and come back the same 36 km upstream?","options":["4.8 hours","5 hours","6 hours","4.5 hours"],"correct":1,"rationale":"Downstream speed = 18 km/h, time = 36 ÷ 18 = 2 h. Upstream speed = 12 km/h, time = 36 ÷ 12 = 3 h. Total = 5 hours."}$aq$),
      ($aq$APT-Q-018$aq$, 2, $aq$quantitative-aptitude$aq$, $aq$percentages$aq$, $aq${"question":"The population of a town increases by 20% in one year and then decreases by 10% in the next year. What is the net change over the two years?","options":["8% increase","10% increase","8% decrease","12% increase"],"correct":0,"rationale":"Net factor = 1.20 × 0.90 = 1.08, i.e. an 8% increase."}$aq$),
      ($aq$APT-Q-019$aq$, 2, $aq$quantitative-aptitude$aq$, $aq$number system$aq$, $aq${"question":"What is the remainder when 2^10 is divided by 7?","options":["1","4","3","2"],"correct":3,"rationale":"2³ = 8 ≡ 1 (mod 7). 2^10 = (2³)³ × 2 ≡ 1 × 2 = 2. (Check: 1024 = 7 × 146 + 2.)"}$aq$),
      ($aq$APT-Q-020$aq$, 2, $aq$quantitative-aptitude$aq$, $aq$time & work$aq$, $aq${"question":"8 men can complete a work in 18 days. After 6 days, 4 more men join them. In how many more days will the remaining work be finished?","options":["12 days","9 days","8 days","10 days"],"correct":2,"rationale":"Total work = 8 × 18 = 144 man-days. Done in 6 days = 48. Left = 96. With 12 men: 96 ÷ 12 = 8 days."}$aq$),
      ($aq$APT-Q-021$aq$, 1, $aq$logical-reasoning$aq$, $aq$number series$aq$, $aq${"question":"Find the next term: 4, 9, 19, 39, 79, ?","options":["158","160","169","159"],"correct":3,"rationale":"Each term = previous × 2 + 1: 4→9→19→39→79→159."}$aq$),
      ($aq$APT-Q-022$aq$, 1, $aq$logical-reasoning$aq$, $aq$letter series$aq$, $aq${"question":"Find the next letter: B, D, G, K, P, ?","options":["V","U","W","T"],"correct":0,"rationale":"Positions 2, 4, 7, 11, 16: gaps +2, +3, +4, +5. Next gap +6 gives 22 = V."}$aq$),
      ($aq$APT-Q-023$aq$, 1, $aq$logical-reasoning$aq$, $aq$coding-decoding$aq$, $aq${"question":"In a certain code, CLOUD is written as DMPVE. How is RAIN written in that code?","options":["QZHM","SBJO","SCKP","TBJO"],"correct":1,"rationale":"Each letter is shifted one place forward: R→S, A→B, I→J, N→O. So SBJO."}$aq$),
      ($aq$APT-Q-024$aq$, 1, $aq$logical-reasoning$aq$, $aq$blood relations$aq$, $aq${"question":"Pointing to a man, Rekha says, \"He is the son of my mother's only brother.\" How is the man related to Rekha?","options":["Brother","Nephew","Cousin","Uncle"],"correct":2,"rationale":"Mother's brother is Rekha's maternal uncle; his son is her maternal cousin."}$aq$),
      ($aq$APT-Q-025$aq$, 1, $aq$logical-reasoning$aq$, $aq$direction sense$aq$, $aq${"question":"Ravi walks 5 km north, turns right and walks 3 km, then turns right again and walks 5 km. How far and in which direction is he from his starting point?","options":["3 km east","3 km west","5 km east","8 km east"],"correct":0,"rationale":"North 5 km, east 3 km, then south 5 km cancels the north movement. He is 3 km east of the start."}$aq$),
      ($aq$APT-Q-026$aq$, 1, $aq$logical-reasoning$aq$, $aq$syllogisms$aq$, $aq${"question":"Statements: All pens are books. Some books are cups.\nConclusions: I. Some pens are cups. II. Some cups are books.","options":["Only I follows","Both I and II follow","Only II follows","Neither I nor II follows"],"correct":2,"rationale":"Some books are cups converts to Some cups are books, so II follows. The pens and cups sets need not overlap, so I does not follow."}$aq$),
      ($aq$APT-Q-027$aq$, 1, $aq$logical-reasoning$aq$, $aq$analogies$aq$, $aq${"question":"Doctor : Hospital :: Teacher : ?","options":["Student","Book","Education","School"],"correct":3,"rationale":"A doctor works in a hospital; a teacher works in a school."}$aq$),
      ($aq$APT-Q-028$aq$, 1, $aq$logical-reasoning$aq$, $aq$odd one out$aq$, $aq${"question":"Find the odd one out: 16, 25, 36, 48, 64","options":["16","48","36","64"],"correct":1,"rationale":"16, 25, 36 and 64 are perfect squares; 48 is not."}$aq$),
      ($aq$APT-Q-029$aq$, 1, $aq$logical-reasoning$aq$, $aq$clocks & calendars$aq$, $aq${"question":"What is the angle between the hour hand and the minute hand of a clock at 4:00?","options":["90°","120°","150°","60°"],"correct":1,"rationale":"Hour hand is at 4 × 30° = 120° from 12; minute hand is at 0°. Angle = 120°."}$aq$),
      ($aq$APT-Q-030$aq$, 1, $aq$logical-reasoning$aq$, $aq$clocks & calendars$aq$, $aq${"question":"If today is Wednesday, what day of the week will it be after 100 days?","options":["Thursday","Saturday","Sunday","Friday"],"correct":3,"rationale":"100 = 14 × 7 + 2, so the day moves 2 ahead: Wednesday + 2 = Friday."}$aq$),
      ($aq$APT-Q-031$aq$, 2, $aq$logical-reasoning$aq$, $aq$number series$aq$, $aq${"question":"Find the next term: 2, 3, 5, 9, 17, ?","options":["31","35","33","34"],"correct":2,"rationale":"Differences are 1, 2, 4, 8, so the next is 16: 17 + 16 = 33."}$aq$),
      ($aq$APT-Q-032$aq$, 2, $aq$logical-reasoning$aq$, $aq$coding-decoding$aq$, $aq${"question":"In a certain code, MANGO is written as NCQKT, where the letters are shifted by 1, 2, 3, 4, 5 places respectively. How is PEARL written?","options":["QGDVQ","QGDUP","QFCUP","QGEVQ"],"correct":0,"rationale":"P+1 = Q, E+2 = G, A+3 = D, R+4 = V, L+5 = Q. So QGDVQ."}$aq$),
      ($aq$APT-Q-033$aq$, 2, $aq$logical-reasoning$aq$, $aq$blood relations$aq$, $aq${"question":"A is the brother of B. B is the daughter of C. C is the wife of D. How is D related to A?","options":["Uncle","Grandfather","Brother-in-law","Father"],"correct":3,"rationale":"B is C's daughter and A is B's brother, so A is C's son. C's husband D is therefore A's father."}$aq$),
      ($aq$APT-Q-034$aq$, 2, $aq$logical-reasoning$aq$, $aq$direction sense$aq$, $aq${"question":"A man starts from point P and walks 8 km east, turns left and walks 6 km, turns left again and walks 8 km, then turns right and walks 2 km. How far and in which direction is he from P?","options":["6 km north","8 km north","10 km north","8 km west"],"correct":1,"rationale":"East 8, then north 6, then west 8 puts him 6 km north of P. Facing west, turning right means facing north; 2 km more gives 8 km north of P."}$aq$),
      ($aq$APT-Q-035$aq$, 2, $aq$logical-reasoning$aq$, $aq$syllogisms$aq$, $aq${"question":"Statements: Some doctors are singers. All singers are dancers. No dancer is a painter.\nConclusions: I. Some doctors are dancers. II. Some singers are painters.","options":["Only I follows","Only II follows","Both I and II follow","Neither I nor II follows"],"correct":0,"rationale":"Some doctors are singers and all singers are dancers, so some doctors are dancers: I follows. Singers are dancers and no dancer is a painter, so no singer is a painter: II is false."}$aq$),
      ($aq$APT-Q-036$aq$, 2, $aq$logical-reasoning$aq$, $aq$seating arrangement$aq$, $aq${"question":"Five friends A, B, C, D and E sit in a row facing north. B is at the extreme right end. A sits second to the left of B. D sits immediately to the left of A. C does not sit at either end. Who sits at the extreme left end?","options":["D","C","E","A"],"correct":2,"rationale":"Positions 1 to 5 from the left: B = 5, A = 3, D = 2. C and E take 1 and 4; C is not at an end so C = 4, E = 1. E is at the extreme left."}$aq$),
      ($aq$APT-Q-037$aq$, 2, $aq$logical-reasoning$aq$, $aq$seating arrangement$aq$, $aq${"question":"Four persons P, Q, R and S sit around a square table facing the centre. P sits opposite Q. R sits to the immediate left of P. Who sits to the immediate right of P?","options":["Q","R","S","Cannot be determined"],"correct":2,"rationale":"P's neighbours are the two persons who are not opposite, R and S. R is on P's left, so S is on P's right."}$aq$),
      ($aq$APT-Q-038$aq$, 2, $aq$logical-reasoning$aq$, $aq$statement & assumption$aq$, $aq${"question":"Statement: The use of mobile phones is banned inside the examination hall.\nAssumptions: I. Mobile phones can be used for malpractice in examinations. II. All students bring mobile phones to the examination hall.","options":["Only I is implicit","Only II is implicit","Both I and II are implicit","Neither I nor II is implicit"],"correct":0,"rationale":"A ban is imposed because of a possible misuse, so I is implicit. The ban does not assume that every student carries a phone, so II is not implicit."}$aq$),
      ($aq$APT-Q-039$aq$, 2, $aq$logical-reasoning$aq$, $aq$data sufficiency$aq$, $aq${"question":"What is the value of x?\nStatement I: x + y = 10.\nStatement II: x − y = 2.","options":["Statement I alone is sufficient","Both statements together are needed","Statement II alone is sufficient","Even both together are not sufficient"],"correct":1,"rationale":"Each statement alone has two unknowns. Together, adding gives 2x = 12, so x = 6."}$aq$),
      ($aq$APT-Q-040$aq$, 2, $aq$logical-reasoning$aq$, $aq$clocks & calendars$aq$, $aq${"question":"What is the angle between the hands of a clock at 7:20?","options":["110°","90°","120°","100°"],"correct":3,"rationale":"Hour hand = 7 × 30 + 20 × 0.5 = 220°. Minute hand = 20 × 6 = 120°. Angle = 220 − 120 = 100°."}$aq$),
      ($aq$APT-Q-041$aq$, 1, $aq$verbal-ability$aq$, $aq$synonyms$aq$, $aq${"question":"Choose the word closest in meaning to ABUNDANT.","options":["Plentiful","Scarce","Rare","Limited"],"correct":0,"rationale":"Abundant means existing in large quantities, i.e. plentiful. The others mean the opposite."}$aq$),
      ($aq$APT-Q-042$aq$, 1, $aq$verbal-ability$aq$, $aq$antonyms$aq$, $aq${"question":"Choose the word opposite in meaning to EXPAND.","options":["Enlarge","Stretch","Contract","Extend"],"correct":2,"rationale":"Expand means to grow larger; its opposite is contract. The others are synonyms."}$aq$),
      ($aq$APT-Q-043$aq$, 1, $aq$verbal-ability$aq$, $aq$fill in the blank$aq$, $aq${"question":"Fill in the blank: The manager was ____ by the team's sincere effort and praised them.","options":["depressed","impressed","suppressed","expressed"],"correct":1,"rationale":"Praise follows a favourable reaction; impressed fits. The other words do not make sense in context."}$aq$),
      ($aq$APT-Q-044$aq$, 1, $aq$verbal-ability$aq$, $aq$fill in the blank$aq$, $aq${"question":"Fill in the blank: Neither of the two answers ____ correct.","options":["are","were","have been","is"],"correct":3,"rationale":"\"Neither\" takes a singular verb, and the statement is in the present tense: is."}$aq$),
      ($aq$APT-Q-045$aq$, 1, $aq$verbal-ability$aq$, $aq$error spotting$aq$, $aq${"question":"Find the part with an error: (A) Each of the students / (B) have submitted / (C) their assignment / (D) No error","options":["(A) Each of the students","(B) have submitted","(C) their assignment","(D) No error"],"correct":1,"rationale":"\"Each\" is singular and needs a singular verb: \"has submitted\". So part B is wrong."}$aq$),
      ($aq$APT-Q-046$aq$, 1, $aq$verbal-ability$aq$, $aq$sentence improvement$aq$, $aq${"question":"Choose the best version of the sentence: \"She did not know where was the station.\"","options":["She did not know where was station.","She did not know where the station was.","She did not know where is the station being.","No improvement is needed."],"correct":1,"rationale":"In an embedded question the normal word order is used: subject before verb, so \"where the station was\"."}$aq$),
      ($aq$APT-Q-047$aq$, 1, $aq$verbal-ability$aq$, $aq$idioms & phrases$aq$, $aq${"question":"Choose the meaning of the idiom: \"To beat around the bush\".","options":["To hit shrubs with a stick","To hunt birds in the wild","To speak indirectly and avoid the main point","To become very angry"],"correct":2,"rationale":"The idiom means to avoid coming straight to the point."}$aq$),
      ($aq$APT-Q-048$aq$, 1, $aq$verbal-ability$aq$, $aq$one-word substitution$aq$, $aq${"question":"Choose one word for: \"An abnormal fear of enclosed spaces\".","options":["Claustrophobia","Agoraphobia","Hydrophobia","Xenophobia"],"correct":0,"rationale":"Claustrophobia is the fear of confined spaces. Agoraphobia is fear of open spaces, hydrophobia of water, xenophobia of strangers."}$aq$),
      ($aq$APT-Q-049$aq$, 1, $aq$verbal-ability$aq$, $aq$fill in the blank$aq$, $aq${"question":"Fill in the blank: She has been living in Pune ____ 2019.","options":["for","since","from","by"],"correct":1,"rationale":"\"Since\" is used with a fixed point in time (2019) with the present perfect continuous tense."}$aq$),
      ($aq$APT-Q-050$aq$, 1, $aq$verbal-ability$aq$, $aq$error spotting$aq$, $aq${"question":"Find the part with an error: (A) He is / (B) senior than me / (C) by five years / (D) No error","options":["(A) He is","(B) senior than me","(C) by five years","(D) No error"],"correct":1,"rationale":"\"Senior\" takes the preposition \"to\", not \"than\": \"senior to me\"."}$aq$),
      ($aq$APT-Q-051$aq$, 2, $aq$verbal-ability$aq$, $aq$synonyms$aq$, $aq${"question":"Choose the word closest in meaning to EPHEMERAL.","options":["Short-lived","Eternal","Fragile","Ordinary"],"correct":0,"rationale":"Ephemeral means lasting for a very short time, so short-lived. Eternal is the opposite."}$aq$),
      ($aq$APT-Q-052$aq$, 2, $aq$verbal-ability$aq$, $aq$antonyms$aq$, $aq${"question":"Choose the word opposite in meaning to BENEVOLENT.","options":["Kind","Generous","Malevolent","Charitable"],"correct":2,"rationale":"Benevolent means well-meaning and kindly; malevolent means wishing harm to others."}$aq$),
      ($aq$APT-Q-053$aq$, 2, $aq$verbal-ability$aq$, $aq$fill in the blank$aq$, $aq${"question":"Fill in the blank: Despite the ____ evidence against him, the accused maintained his innocence.","options":["negligible","scanty","overwhelming","doubtful"],"correct":2,"rationale":"\"Despite\" signals contrast: he claimed innocence even though the evidence was very strong, hence overwhelming."}$aq$),
      ($aq$APT-Q-054$aq$, 2, $aq$verbal-ability$aq$, $aq$fill in the blank$aq$, $aq${"question":"Fill in the blank: Had I known about the strike, I ____ stayed at home.","options":["would have","will have","had","would"],"correct":0,"rationale":"This is a third conditional: \"Had + past participle ... would have + past participle\"."}$aq$),
      ($aq$APT-Q-055$aq$, 2, $aq$verbal-ability$aq$, $aq$sentence improvement$aq$, $aq${"question":"Choose the best version: \"The team captain, along with his players, were greeted by the crowd.\"","options":["The team captain, along with his players, have been greeted by the crowd.","The team captain, along with his players, were being greeted by the crowd.","No improvement is needed.","The team captain, along with his players, was greeted by the crowd."],"correct":3,"rationale":"The subject is \"captain\" (singular); \"along with his players\" does not change the number. So the verb is \"was\"."}$aq$),
      ($aq$APT-Q-056$aq$, 2, $aq$verbal-ability$aq$, $aq$idioms & phrases$aq$, $aq${"question":"Choose the meaning of the idiom: \"To bite the bullet\".","options":["To eat hurriedly","To face an unpleasant situation bravely","To speak rudely","To avoid a difficult task"],"correct":1,"rationale":"The idiom means to accept and endure something painful or unpleasant with courage."}$aq$),
      ($aq$APT-Q-057$aq$, 2, $aq$verbal-ability$aq$, $aq$one-word substitution$aq$, $aq${"question":"Choose one word for: \"A speech delivered without any preparation\".","options":["Soliloquy","Monologue","Oration","Extempore"],"correct":3,"rationale":"An extempore speech is delivered without preparation. A soliloquy is speaking to oneself; a monologue is a long speech by one person; an oration is a formal speech."}$aq$),
      ($aq$APT-Q-058$aq$, 2, $aq$verbal-ability$aq$, $aq$para-jumble$aq$, $aq${"question":"Arrange the sentences in a logical order.\nP: So Ravi woke up late.\nQ: The alarm did not ring on Monday.\nR: He reached the station only at 8 a.m.\nS: By then, the train had already left.","options":["PQRS","QRPS","QPRS","RSQP"],"correct":2,"rationale":"Q gives the cause (alarm failure), P the result (waking late), R his arrival, and S the consequence (train gone). Order: QPRS."}$aq$),
      ($aq$APT-Q-059$aq$, 2, $aq$verbal-ability$aq$, $aq$reading comprehension$aq$, $aq${"question":"Passage: Water scarcity in many Indian cities is not only a result of low rainfall. Poor maintenance of pipelines leads to large leakages, and unchecked groundwater extraction lowers water tables every year. Experts argue that rainwater harvesting and repairing old pipes can ease the problem faster than building new dams.\nQuestion: According to the passage, what can ease the problem faster than building new dams?","options":["Extracting more groundwater","Rainwater harvesting and repairing old pipes","Waiting for higher rainfall","Building more pipelines"],"correct":1,"rationale":"The last sentence states that rainwater harvesting and repairing old pipes can ease the problem faster than new dams."}$aq$),
      ($aq$APT-Q-060$aq$, 2, $aq$verbal-ability$aq$, $aq$reading comprehension$aq$, $aq${"question":"Passage: Water scarcity in many Indian cities is not only a result of low rainfall. Poor maintenance of pipelines leads to large leakages, and unchecked groundwater extraction lowers water tables every year. Experts argue that rainwater harvesting and repairing old pipes can ease the problem faster than building new dams.\nQuestion: Which of the following is NOT mentioned in the passage as a cause of water scarcity?","options":["Pollution of rivers by industries","Leakage from pipelines","Unchecked groundwater extraction","Low rainfall"],"correct":0,"rationale":"The passage mentions low rainfall, pipeline leakages and groundwater extraction. River pollution is never mentioned."}$aq$)
    ) AS v(ext_id, level_pos, cat_slug, topic, content)
    JOIN levels lv ON lv.pack_id = v_pack AND lv.position = v.level_pos
    JOIN categories c ON c.tenant_id = v_platform AND c.domain_id = v_domain AND c.slug = v.cat_slug
  ON CONFLICT (id) DO NOTHING;

  -- 7. v1 snapshot (what publishPack writes before bumping version 1 -> 2).
  INSERT INTO question_versions (question_id, version, content, rubric, saved_by)
  SELECT q.id, 1, q.content, q.rubric, v_user
    FROM questions q
   WHERE q.pack_id = v_pack AND q.id IN (SELECT md5('assessiq:aptitude:' || e)::uuid FROM unnest(ARRAY[$aq$APT-Q-001$aq$, $aq$APT-Q-002$aq$, $aq$APT-Q-003$aq$, $aq$APT-Q-004$aq$, $aq$APT-Q-005$aq$, $aq$APT-Q-006$aq$, $aq$APT-Q-007$aq$, $aq$APT-Q-008$aq$, $aq$APT-Q-009$aq$, $aq$APT-Q-010$aq$, $aq$APT-Q-011$aq$, $aq$APT-Q-012$aq$, $aq$APT-Q-013$aq$, $aq$APT-Q-014$aq$, $aq$APT-Q-015$aq$, $aq$APT-Q-016$aq$, $aq$APT-Q-017$aq$, $aq$APT-Q-018$aq$, $aq$APT-Q-019$aq$, $aq$APT-Q-020$aq$, $aq$APT-Q-021$aq$, $aq$APT-Q-022$aq$, $aq$APT-Q-023$aq$, $aq$APT-Q-024$aq$, $aq$APT-Q-025$aq$, $aq$APT-Q-026$aq$, $aq$APT-Q-027$aq$, $aq$APT-Q-028$aq$, $aq$APT-Q-029$aq$, $aq$APT-Q-030$aq$, $aq$APT-Q-031$aq$, $aq$APT-Q-032$aq$, $aq$APT-Q-033$aq$, $aq$APT-Q-034$aq$, $aq$APT-Q-035$aq$, $aq$APT-Q-036$aq$, $aq$APT-Q-037$aq$, $aq$APT-Q-038$aq$, $aq$APT-Q-039$aq$, $aq$APT-Q-040$aq$, $aq$APT-Q-041$aq$, $aq$APT-Q-042$aq$, $aq$APT-Q-043$aq$, $aq$APT-Q-044$aq$, $aq$APT-Q-045$aq$, $aq$APT-Q-046$aq$, $aq$APT-Q-047$aq$, $aq$APT-Q-048$aq$, $aq$APT-Q-049$aq$, $aq$APT-Q-050$aq$, $aq$APT-Q-051$aq$, $aq$APT-Q-052$aq$, $aq$APT-Q-053$aq$, $aq$APT-Q-054$aq$, $aq$APT-Q-055$aq$, $aq$APT-Q-056$aq$, $aq$APT-Q-057$aq$, $aq$APT-Q-058$aq$, $aq$APT-Q-059$aq$, $aq$APT-Q-060$aq$]) AS e)
  ON CONFLICT (question_id, version) DO NOTHING;

  -- 8. Integrity guard: every expected question must exist (a silent JOIN drop would fail here).
  SELECT count(*) INTO v_have FROM questions
   WHERE pack_id = v_pack AND id IN (SELECT md5('assessiq:aptitude:' || e)::uuid
         FROM unnest(ARRAY[$aq$APT-Q-001$aq$, $aq$APT-Q-002$aq$, $aq$APT-Q-003$aq$, $aq$APT-Q-004$aq$, $aq$APT-Q-005$aq$, $aq$APT-Q-006$aq$, $aq$APT-Q-007$aq$, $aq$APT-Q-008$aq$, $aq$APT-Q-009$aq$, $aq$APT-Q-010$aq$, $aq$APT-Q-011$aq$, $aq$APT-Q-012$aq$, $aq$APT-Q-013$aq$, $aq$APT-Q-014$aq$, $aq$APT-Q-015$aq$, $aq$APT-Q-016$aq$, $aq$APT-Q-017$aq$, $aq$APT-Q-018$aq$, $aq$APT-Q-019$aq$, $aq$APT-Q-020$aq$, $aq$APT-Q-021$aq$, $aq$APT-Q-022$aq$, $aq$APT-Q-023$aq$, $aq$APT-Q-024$aq$, $aq$APT-Q-025$aq$, $aq$APT-Q-026$aq$, $aq$APT-Q-027$aq$, $aq$APT-Q-028$aq$, $aq$APT-Q-029$aq$, $aq$APT-Q-030$aq$, $aq$APT-Q-031$aq$, $aq$APT-Q-032$aq$, $aq$APT-Q-033$aq$, $aq$APT-Q-034$aq$, $aq$APT-Q-035$aq$, $aq$APT-Q-036$aq$, $aq$APT-Q-037$aq$, $aq$APT-Q-038$aq$, $aq$APT-Q-039$aq$, $aq$APT-Q-040$aq$, $aq$APT-Q-041$aq$, $aq$APT-Q-042$aq$, $aq$APT-Q-043$aq$, $aq$APT-Q-044$aq$, $aq$APT-Q-045$aq$, $aq$APT-Q-046$aq$, $aq$APT-Q-047$aq$, $aq$APT-Q-048$aq$, $aq$APT-Q-049$aq$, $aq$APT-Q-050$aq$, $aq$APT-Q-051$aq$, $aq$APT-Q-052$aq$, $aq$APT-Q-053$aq$, $aq$APT-Q-054$aq$, $aq$APT-Q-055$aq$, $aq$APT-Q-056$aq$, $aq$APT-Q-057$aq$, $aq$APT-Q-058$aq$, $aq$APT-Q-059$aq$, $aq$APT-Q-060$aq$]) AS e);
  IF v_have <> 60 THEN
    RAISE EXCEPTION '0109: expected 60 aptitude questions, found %', v_have;
  END IF;
END
$aptmig$;
