/**
 * Integration test: 0109_seed_platform_aptitude_pack (generated by
 * tools/gen-aptitude-migration.ts).
 *
 * Real Postgres (postgres:16-alpine testcontainer). The full repo migration chain
 * (every modules/star/migrations/*.sql below 0109, lexical by basename — same order as
 * tools/migrate.ts) is applied ONCE to a template database; each scenario clones it.
 *
 * Covers: domain + categories (platform + propagation, tenant-local domain untouched),
 * pack/levels/questions, MCQ content vs the repo's McqContentSchema, SQL-escape
 * round-trip, re-apply is a no-op, publish mode invariants, clone-on-use of the
 * published pack, and the real 0109 file in docs/exam-content/ (when present locally;
 * it is gitignored because it holds answer keys, so CI skips that block).
 */

import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { GenericContainer, Wait, type StartedTestContainer } from "testcontainers";
import { Client } from "pg";
import { readdir, readFile, access } from "node:fs/promises";
import { join, basename } from "node:path";
import { randomUUID } from "node:crypto";
import { McqContentSchema } from "../types.js";
import { clonePackToTenant } from "../clone.js";
import {
  generateAptitudeSql,
  PACK_SLUG,
  type AptitudeInput,
} from "../../../../tools/gen-aptitude-migration.js";

const toFs = (u: URL) => u.pathname.replace(/^\/([A-Za-z]:)/, "$1");
const HERE = toFs(new URL(".", import.meta.url));
const MODULES = join(HERE, "..", "..", "..");
// Real content lives outside git (public repo) — present only on a machine that holds docs/exam-content/.
const REAL_0109 = join(MODULES, "..", "docs", "exam-content", "0109_seed_platform_aptitude_pack.sql");

let container: StartedTestContainer;
let baseUrl: (db: string) => string;

async function withClient<T>(db: string, fn: (c: Client) => Promise<T>): Promise<T> {
  const c = new Client({ connectionString: baseUrl(db) });
  await c.connect();
  try {
    return await fn(c);
  } finally {
    await c.end();
  }
}

async function migrationFilesBefore0109(): Promise<string[]> {
  const files: string[] = [];
  for (const m of await readdir(MODULES, { withFileTypes: true })) {
    if (!m.isDirectory() || m.name === "node_modules") continue;
    const dir = join(MODULES, m.name, "migrations");
    let entries: string[];
    try {
      entries = await readdir(dir);
    } catch {
      continue;
    }
    for (const e of entries) if (e.endsWith(".sql")) files.push(join(dir, e));
  }
  // Fresh-DB dependency order: tenancy 0001-0004, users 020-021, auth 010-016, then 4-digit
  // files numerically. (Plain lexical order — what tools/migrate.ts
  // uses against an already-bootstrapped DB — would run 0010 before users exists.)
  const key = (f: string): [number, number, string] => {
    const name = basename(f);
    const prefix = name.split("_")[0]!;
    const n = parseInt(prefix, 10);
    return [n <= 4 ? 0 : prefix.length === 3 ? (n >= 20 ? 1 : 2) : 3, n, name];
  };
  return files
    .filter((f) => parseInt(basename(f), 10) < 109)
    .sort((a, b) => {
      const [ga, na, sa] = key(a);
      const [gb, nb, sb] = key(b);
      return ga - gb || na - nb || sa.localeCompare(sb);
    });
}

let platformId: string;
let tenantA: string;
let tenantB: string;
let tenantLocal: string; // has a tenant-LOCAL 'aptitude' domain
let platformUser: string;

async function cloneDb(name: string): Promise<void> {
  await withClient("postgres", (c) => c.query(`CREATE DATABASE ${name} TEMPLATE tpl`));
}

const fixture = JSON.parse(
  await readFile(join(HERE, "fixtures", "aptitude-sample.json"), "utf8"),
) as AptitudeInput;

beforeAll(async () => {
  container = await new GenericContainer("postgres:16-alpine")
    .withEnvironment({ POSTGRES_USER: "test", POSTGRES_PASSWORD: "test", POSTGRES_DB: "postgres" })
    .withExposedPorts(5432)
    .withWaitStrategy(Wait.forLogMessage(/database system is ready to accept connections/, 2))
    .withStartupTimeout(60_000)
    .start();
  baseUrl = (db) => `postgres://test:test@${container.getHost()}:${container.getMappedPort(5432)}/${db}`;

  await withClient("postgres", (c) => c.query("CREATE DATABASE tpl"));
  await withClient("tpl", async (c) => {
    for (const f of await migrationFilesBefore0109()) {
      try {
        await c.query(await readFile(f, "utf8"));
      } catch (e) {
        throw new Error(`migration ${basename(f)} failed: ${(e as Error).message}`);
      }
    }
    // N21: the 0109 seed predates question_versions.type (0156); app code (clone) now writes it,
    // so add the column to the template AFTER the pre-0109 chain (0109 itself is applied per scenario).
    await c.query(await readFile(join(MODULES, "04-question-bank", "migrations", "0156_question_versions_type_n21.sql"), "utf8"));
    // 016_super_admin.sql already bootstraps the platform tenant + super_admin user.
    platformId = "00000000-0000-7000-0000-000000000001";
    platformUser = "00000000-0000-7000-0000-000000000002";
    tenantA = randomUUID();
    tenantB = randomUUID();
    tenantLocal = randomUUID();
    await c.query(
      `INSERT INTO tenants (id, slug, name) VALUES ($1,'co-a','A'),($2,'co-b','B'),($3,'co-local','L')`,
      [tenantA, tenantB, tenantLocal],
    );
    await c.query(
      `INSERT INTO domains (tenant_id, slug, name, source, status, display_order)
       VALUES ($1,'aptitude','My Own Aptitude','tenant','active',1)`,
      [tenantLocal],
    );
  });
  // A template DB cannot be cloned while connected — withClient closed its connection.
}, 240_000);

afterAll(async () => {
  if (container !== undefined) await container.stop();
});

const apply = (db: string, sql: string) => withClient(db, (c) => c.query(sql));
const q = <T extends Record<string, unknown>>(db: string, sql: string, p: unknown[] = []) =>
  withClient(db, async (c) => (await c.query<T>(sql, p)).rows);

/** Stable fingerprint of everything the migration writes (for the no-op check). */
const FINGERPRINT = `
  SELECT
   (SELECT md5(string_agg(d::text, '|' ORDER BY d.tenant_id, d.slug)) FROM domains d WHERE d.slug='aptitude') AS dom,
   (SELECT md5(string_agg(c::text, '|' ORDER BY c.id)) FROM categories c JOIN domains d ON d.id=c.domain_id WHERE d.slug='aptitude') AS cat,
   (SELECT md5(string_agg(p::text, '|' ORDER BY p.id)) FROM question_packs p WHERE p.slug='${PACK_SLUG}') AS pack,
   (SELECT md5(string_agg(l::text, '|' ORDER BY l.id)) FROM levels l JOIN question_packs p ON p.id=l.pack_id WHERE p.slug='${PACK_SLUG}') AS lvl,
   (SELECT md5(string_agg(x::text, '|' ORDER BY x.id)) FROM questions x JOIN question_packs p ON p.id=x.pack_id WHERE p.slug='${PACK_SLUG}') AS qs,
   (SELECT count(*) FROM question_versions v JOIN questions x ON x.id=v.question_id JOIN question_packs p ON p.id=x.pack_id WHERE p.slug='${PACK_SLUG}') AS qv`;

describe("0109 aptitude seed — draft mode (fixture)", () => {
  const DB = "draft_db";
  const sql = generateAptitudeSql(fixture);

  beforeAll(async () => {
    await cloneDb(DB);
    await apply(DB, sql);
  }, 120_000);

  it("creates the platform domain and propagates it (tenant-local domain untouched)", async () => {
    const rows = await q<{ tenant_id: string; source: string; name: string }>(
      DB,
      `SELECT tenant_id, source, name FROM domains WHERE slug='aptitude'`,
    );
    const by = new Map(rows.map((r) => [r.tenant_id, r]));
    expect(rows).toHaveLength(4);
    for (const t of [platformId, tenantA, tenantB]) expect(by.get(t)?.source).toBe("platform");
    expect(by.get(platformId)?.name).toBe("Aptitude");
    expect(by.get(tenantLocal)).toMatchObject({ source: "tenant", name: "My Own Aptitude" });
  });

  it("creates 3 MCQ-only categories in platform + platform-origin tenants, none under tenant-local", async () => {
    const rows = await q<{ tenant_id: string; slug: string; supported_types: string[] }>(
      DB,
      `SELECT c.tenant_id, c.slug, c.supported_types FROM categories c JOIN domains d ON d.id=c.domain_id WHERE d.slug='aptitude'`,
    );
    for (const t of [platformId, tenantA, tenantB]) {
      const mine = rows.filter((r) => r.tenant_id === t).map((r) => r.slug).sort();
      expect(mine).toEqual(["logical-reasoning", "quantitative-aptitude", "verbal-ability"]);
    }
    expect(rows.filter((r) => r.tenant_id === tenantLocal)).toHaveLength(0);
    expect(rows.every((r) => JSON.stringify(r.supported_types) === '["mcq"]')).toBe(true);
  });

  it("creates the draft platform pack with L1/L2 levels and all questions", async () => {
    const [pack] = await q<{ id: string; tenant_id: string; status: string; version: number; domain: string; name: string }>(
      DB,
      `SELECT id, tenant_id, status, version, domain, name FROM question_packs WHERE slug=$1`,
      [PACK_SLUG],
    );
    expect(pack).toMatchObject({ tenant_id: platformId, status: "draft", version: 1, domain: "aptitude", name: fixture.pack.name });
    const lv = await q<{ position: number; label: string; default_question_count: number }>(
      DB,
      `SELECT position, label, default_question_count FROM levels WHERE pack_id=$1 ORDER BY position`,
      [pack!.id],
    );
    expect(lv).toEqual([
      { position: 1, label: "L1", default_question_count: 2 },
      { position: 2, label: "L2", default_question_count: 1 },
    ]);
    const qs = await q<{ type: string; points: number; status: string; version: number; topic: string; category_slug: string; domain_slug: string }>(
      DB,
      `SELECT x.type, x.points, x.status, x.version, x.topic, c.slug AS category_slug, d.slug AS domain_slug
         FROM questions x JOIN categories c ON c.id=x.category_id JOIN domains d ON d.id=x.domain_id
        WHERE x.pack_id=$1 AND c.tenant_id=$2 ORDER BY x.topic`,
      [pack!.id, platformId],
    );
    expect(qs).toHaveLength(fixture.questions.length);
    expect(qs.every((r) => r.type === "mcq" && r.points === 1 && r.status === "draft" && r.version === 1 && r.domain_slug === "aptitude")).toBe(true);
    // draft mode writes NO version snapshots (publishPack does, from the UI)
    const [nv] = await q<{ n: string }>(DB, `SELECT count(*)::text AS n FROM question_versions`);
    expect(nv!.n).toBe("0");
  });

  it("stores content that passes McqContentSchema and round-trips the exact text", async () => {
    const rows = await q<{ content: unknown }>(
      DB,
      `SELECT x.content FROM questions x JOIN question_packs p ON p.id=x.pack_id WHERE p.slug=$1`,
      [PACK_SLUG],
    );
    const stems = new Set<string>();
    for (const r of rows) {
      const parsed = McqContentSchema.safeParse(r.content);
      expect(parsed.success, JSON.stringify(parsed)).toBe(true);
      if (parsed.success) stems.add(parsed.data.question);
    }
    for (const f of fixture.questions) {
      expect(stems.has(f.stem), `stem for ${f.id}`).toBe(true);
    }
    const one = rows.map((r) => r.content as { question: string; correct: number; rationale: string })
      .find((c) => c.question === fixture.questions[0]!.stem)!;
    expect(one.correct).toBe(fixture.questions[0]!.correct_index);
    expect(one.rationale).toBe(fixture.questions[0]!.explanation);
  });

  it("re-applying is a no-op", async () => {
    const before = await q(DB, FINGERPRINT);
    await apply(DB, sql);
    await apply(DB, sql);
    expect(await q(DB, FINGERPRINT)).toEqual(before);
  });
});

describe("0109 aptitude seed — skips cleanly without a platform user", () => {
  it("is a NOTICE-only no-op when no platform admin exists", async () => {
    await cloneDb("nouser_db");
    await apply("nouser_db", `UPDATE users SET status='disabled' WHERE tenant_id='${platformId}'`);
    await apply("nouser_db", generateAptitudeSql(fixture));
    expect(await q("nouser_db", `SELECT 1 FROM question_packs WHERE slug='${PACK_SLUG}'`)).toHaveLength(0);
  }, 60_000);
});

describe("0109 aptitude seed — publish mode (fixture)", () => {
  const DB = "pub_db";

  beforeAll(async () => {
    await cloneDb(DB);
    await apply(DB, generateAptitudeSql(fixture, { publish: true }));
  }, 120_000);

  it("matches the post-publishPack state: pack published v2, questions active v2 + qv v1", async () => {
    const [pack] = await q<{ status: string; version: number }>(DB, `SELECT status, version FROM question_packs WHERE slug=$1`, [PACK_SLUG]);
    expect(pack).toMatchObject({ status: "published", version: 2 });
    const rows = await q<{ status: string; version: number; maxqv: number; same: boolean }>(
      DB,
      `SELECT x.status, x.version,
              (SELECT MAX(v.version) FROM question_versions v WHERE v.question_id=x.id) AS maxqv,
              (SELECT v.content = x.content FROM question_versions v WHERE v.question_id=x.id AND v.version=1) AS same
         FROM questions x JOIN question_packs p ON p.id=x.pack_id WHERE p.slug=$1`,
      [PACK_SLUG],
    );
    expect(rows).toHaveLength(fixture.questions.length);
    for (const r of rows) {
      expect(r.status).toBe("active");
      expect(r.version).toBe(2);
      expect(r.maxqv).toBe(1); // invariant: questions.version = MAX(qv.version) + 1
      expect(r.same).toBe(true);
    }
  });

  it("re-applying is a no-op", async () => {
    const before = await q(DB, FINGERPRINT);
    await apply(DB, generateAptitudeSql(fixture, { publish: true }));
    expect(await q(DB, FINGERPRINT)).toEqual(before);
  });

  it("the published pack clones into a company tenant with every question (clone-on-use)", async () => {
    const [pk] = await q<{ id: string }>(DB, `SELECT id FROM question_packs WHERE slug=$1`, [PACK_SLUG]);
    const packId = pk!.id;
    const res = await withClient(DB, async (c) => {
      await c.query("BEGIN");
      await c.query("SET LOCAL ROLE assessiq_system");
      const r = await clonePackToTenant(c as never, packId, tenantA, platformUser);
      await c.query("COMMIT");
      return r;
    });
    expect(res).toMatchObject({ questionCount: fixture.questions.length, skippedCount: 0, reusedExisting: false });
  });
});

describe.skipIf(!(await access(REAL_0109).then(() => true, () => false)))(
  "committed 0109 migration (real content)",
  () => {
    const DB = "real_db";
    let sql: string;

    beforeAll(async () => {
      sql = await readFile(REAL_0109, "utf8");
      await cloneDb(DB);
      await apply(DB, sql);
    }, 120_000);

    it("every question validates against McqContentSchema and counts are consistent", async () => {
      const rows = await q<{ content: unknown; points: number; level_pos: number; cat: string }>(
        DB,
        `SELECT x.content, x.points, l.position AS level_pos, c.slug AS cat
           FROM questions x JOIN question_packs p ON p.id=x.pack_id
           JOIN levels l ON l.id=x.level_id JOIN categories c ON c.id=x.category_id
          WHERE p.slug=$1`,
        [PACK_SLUG],
      );
      expect(rows.length).toBeGreaterThan(0);
      const m = /questions: (\d+)/.exec(sql);
      expect(rows.length).toBe(Number(m![1]));
      for (const r of rows) {
        expect(McqContentSchema.safeParse(r.content).success).toBe(true);
        expect(r.points).toBe(1);
        expect([1, 2]).toContain(r.level_pos);
        expect(["quantitative-aptitude", "logical-reasoning", "verbal-ability"]).toContain(r.cat);
      }
    });

    it("re-applying is a no-op", async () => {
      const before = await q(DB, FINGERPRINT);
      await apply(DB, sql);
      expect(await q(DB, FINGERPRINT)).toEqual(before);
    });
  },
);
