-- generated by tools/generate-help-seed.ts on 2026-05-01T16:54:45.800Z
-- DO NOT EDIT BY HAND. Re-run the generator after editing YAML:
--   pnpm tsx tools/generate-help-seed.ts
--
-- Idempotency: ON CONFLICT (tenant_id, key, locale, version) DO NOTHING
-- means re-running this migration after a YAML edit does not change v1
-- rows already seeded. To update content, use the upsertHelp service
-- (which bumps version). Global rows (tenant_id IS NULL) are inserted as
-- the postgres superuser which BYPASSes RLS — the app role cannot insert
-- global rows per the INSERT policy on help_content.

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.auth.login.tenant_slug',
  'admin',
  'en',
  'Your organization''s slug — the unique URL-safe ID we issued during onboarding (e.g. wipro-soc).',
  $$## Tenant slug

Each AssessIQ tenant has a short, URL-safe identifier you'll use at every
sign-in. It usually mirrors your team or product name (e.g. `wipro-soc`,
`acme-secops`). Your AssessIQ administrator received the slug at onboarding;
if you don't have it, ask them — it is not the same as your email domain.

The slug is also used in webhook payloads and embed-iframe URLs, so once it
is set it stays stable. Renaming a tenant is a manual operation that
requires support.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.auth.mfa.enroll_vs_verify',
  'admin',
  'en',
  'First-time admins enroll an authenticator app here; returning admins enter their 6-digit code to sign in.',
  $$## TOTP enrollment vs verification

The first time an admin signs in, AssessIQ shows a QR code and asks you to
scan it with an authenticator app (Google Authenticator, Authy, 1Password,
Microsoft Authenticator). After scanning, enter the 6-digit code shown in
the app to confirm the secret matches.

Returning admins skip the QR code and only enter the 6-digit code. Codes
rotate every 30 seconds; AssessIQ accepts the previous, current, and next
code to absorb small clock drifts.

Lockout policy: five wrong codes in a row locks the account for 15 minutes.
Recovery codes are not yet supported in Phase 1 — if you lose access,
another admin must reset your TOTP enrollment.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.users.role',
  'admin',
  'en',
  'admin = full access · reviewer = grade and override only · candidate = take assessments only.',
  $$## User roles

| Role | Can do |
|---|---|
| **admin** | Everything: tenant settings, packs, assessments, grading, exports, billing |
| **reviewer** | Grade and override AI verdicts; view assessment results; cannot edit packs or invite users |
| **candidate** | Take assigned assessments; view their own past scores |

Role changes take effect on the next sign-in for that user. Demoting an
admin to reviewer revokes their fresh-MFA gates immediately. There is no
"owner" or "billing" role — that is a Phase 2 concern.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.packs.create.domain',
  'admin',
  'en',
  'The role-readiness domain this pack covers (SOC analyst, DevOps, etc.). Set once; choose carefully.',
  $$## Pack domain

A *pack* is a collection of leveled questions for a single role-readiness
domain. The domain is metadata only — AssessIQ has no domain-specific
code paths — but it controls the default rubric anchors, the example UI
copy, and how packs sort in the admin browser.

Common values: `soc-analyst`, `devops-engineer`, `cloud-architect`,
`identity-engineer`, `incident-responder`. Use lowercase, dash-separated.

You cannot rename a pack's domain after questions exist under it — clone
the pack into a new domain instead.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.questions.generate.draft',
  'admin',
  'en',
  'AI-assisted question drafts are a Phase 2 feature; for now, author by hand or import from JSON.',
  $$## AI-assisted question generation

Phase 2 will add a **Generate draft** button that takes a one-line prompt
("design a tier-2 SOC scenario about phishing escalation") and returns a
fully-shaped question with anchors, rubric bands, and example responses,
using the same AI-grading pipeline that scores attempts.

For Phase 1 you have two paths:

1. **Author by hand** — fill the question form (type, body, expected
   answers, rubric) directly.
2. **Import JSON** — paste or upload a JSON document conforming to the
   schema in `modules/04-question-bank/import.schema.json`.

The hand-authored path supports every question type the engine understands;
JSON import is convenient for migrating from spreadsheets.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.questions.import.format',
  'admin',
  'en',
  'JSON only in Phase 1 (CSV is Phase 2). Schema: modules/04-question-bank/import.schema.json.',
  $$## Question import format

Bulk import accepts a single JSON document in this Phase. The document
schema is published at
`modules/04-question-bank/import.schema.json`; in summary:

```jsonc
{
  "pack": "soc-analyst-v1",
  "level": "L2",
  "questions": [
    {
      "type": "mcq | kql | scenario | subjective",
      "body": "...",
      "answers": [...],          // shape varies by type
      "rubric": { ... },         // for subjective / scenario
      "tags": ["phishing", "triage"]
    }
  ]
}
```

CSV import is on the Phase 2 roadmap. Until then, convert spreadsheets to
JSON with a script of your choice — the schema is plain enough to template.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.questions.type.kql.expected_keywords',
  'admin',
  'en',
  'Tokens that MUST appear (case-insensitive) for the answer to score above band 0. Add 1–5 per question.',
  $$## KQL expected keywords

KQL questions are graded on a hybrid: **deterministic keyword presence**
plus AI judgement on syntactic and semantic correctness. The keyword list
is the deterministic floor — if none of the listed tokens appear in the
candidate's query, the answer can score at most band 0 regardless of how
elegant the rest of the query is.

**Recommendations:**

- Pick tokens that are *necessary*, not sufficient: a query that lacks
  `where` or the target table cannot be correct.
- 1–5 keywords per question. More than 5 makes scoring brittle.
- Use case-insensitive matching (`Where`, `where`, `WHERE` all match).
- Quoted identifiers (`"My Table"`) are matched literally; bare tokens
  are matched as whole words (`time` will not match `timestamp`).

The AI grader sees the keyword list as a hint and uses it to anchor its
own judgement — admin can still override.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.questions.type.scenario.step_dependency',
  'admin',
  'en',
  'Lock a step so it can''t be answered until the previous step is submitted. Use sparingly.',
  $$## Step dependency

Scenario questions present a multi-step incident. By default, candidates
can navigate freely — they may answer step 3 before step 1 if they want
to think non-linearly. Setting **step dependency** locks each step until
the previous one is submitted.

**When to enable:**

- The branching narrative (we tell the candidate "the alert escalated
  because…") would spoil the answer to an earlier step.
- You want to measure pure decision speed without back-tracking.

**When not to:**

- Standard triage workflows. Real analysts revisit earlier conclusions.
- Investigation-style scenarios where evidence accumulates.

The candidate sees a small lock icon on dependent steps and a clear
"Submit step N to continue" prompt.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.questions.type.subjective.rubric',
  'admin',
  'en',
  'Anchors describe each band (0/25/50/75/100). Write band 100 first, then 0, then fill the middle.',
  $$## Subjective rubric anchors

AI grading uses the rubric anchors as the *one* shared truth between the
AI's judgement and your override. Every grading record stores the anchors
that were active at grade time, so an audit trail survives even if you
later refine the rubric.

**Authoring approach that works:**

1. Write **band 100** first — what does an obviously correct, complete
   answer look like? Be specific: which terms, structures, or tradeoffs
   must appear.
2. Write **band 0** second — what is missing, vague, or wrong enough to
   score zero? The AI uses this as the negative anchor.
3. Fill **band 50** — the middle: partial credit, missing one of two
   required elements, correct intuition with weak rationale.
4. Fill **band 25** and **band 75** by interpolation.

**Anti-patterns:**

- "It depends" or "looks reasonable" — too vague for the AI to ground on.
- Numeric thresholds the AI can't verify (e.g. "discusses at least three
  mitigations" works; "scores 7/10 on accuracy" doesn't).
- More than ~80 words per band — the rubric is a contract, not an essay.

Override the AI verdict any time. Your override sits *beside* the AI's
record, never replaces it.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.assessments.create.duration',
  'admin',
  'en',
  'Total wall-clock minutes from candidate start to auto-submit. L1: 30–45, L2: 45–60, L3: 60–90.',
  $$## Duration

The total time a candidate has from clicking **Begin Assessment** to the
auto-submit. Once started, the timer cannot be paused.

**Recommendations:**

- **L1 / triage-style:** 30–45 minutes
- **L2 / investigation:** 45–60 minutes
- **L3 / detection engineering:** 60–90 minutes

Candidates can navigate freely between questions during this window.
Auto-submit fires the moment the timer hits zero — partial answers are
saved.

> **Note:** Time-based behavioral signals (per-question time spent, edits)
> are captured regardless of duration. Do not compress duration to "force
> speed"; the platform measures speed separately.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.assessments.create.question_count',
  'admin',
  'en',
  'How many questions to draw from the pack/level pool. Must be ≤ active questions in the pool.',
  $$## Question count

AssessIQ samples this many questions from the pack + level you chose. If
randomization is on, every candidate sees a different draw; if off, all
candidates see the same set in the same order.

**Constraints:**

- Must be ≤ the number of `active` questions in the pool. Publish fails
  if not.
- Pool size is shown live next to this input as you author.
- Recommended ratio: ~1 question per 4 minutes of duration. Higher density
  is fine for MCQ-heavy assessments; lower for scenario or subjective
  heavy ones.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.assessments.create.randomize',
  'admin',
  'en',
  'Each candidate sees a different sample + order. Off = identical assessment for everyone.',
  $$## Randomize question selection

With randomization on, every candidate's attempt:

- Draws a fresh sample from the pool (size = question count).
- Shuffles question order.
- Shuffles MCQ answer order on a per-question basis.

The seed is stable per attempt, so refreshing the page does not re-shuffle.

**When to turn it off:**

- Calibrating a new pack against a fixed reference set.
- Live training events where everyone sees the same screen.
- Anti-cheat is **not** the right reason — randomization is not a
  meaningful integrity control. Use real-time monitoring or proctoring
  tools instead.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.assessments.publish',
  'admin',
  'en',
  'Locks the question set, opens invitations, and starts the schedule. Pre-flight checks run automatically.',
  $$## Publish assessment

Publishing flips the assessment from `draft` to `published` and runs three
pre-flight checks:

1. **Pool size** — the active question pool ≥ the requested question
   count.
2. **Open window** — `opens_at` is in the future or already past with a
   valid `closes_at`.
3. **Notification config** — if invitations are scheduled, the tenant has
   a working SMTP config.

Once published, the question set is **frozen** for that assessment. Edits
to questions in the underlying pack do not affect already-published
assessments — that is by design (HR auditability).

To change a published assessment, **close** it and create a new one.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.assessments.close.early',
  'admin',
  'en',
  'Sends auto-submit to every in-progress attempt. Cannot be undone — closes the schedule immediately.',
  $$## Close assessment early

Forces the assessment from `active` to `closed` immediately, regardless of
`closes_at`. Effects:

- Every in-progress attempt is auto-submitted with whatever answers exist.
- Pending invitations are revoked; their links return a "this assessment
  is closed" page if used.
- Notifications fire as if the schedule had ended naturally.

**You cannot reopen** a closed assessment whose `closes_at` has passed.
Re-opening before `closes_at` is allowed but rare — see
`assessment.reopen` (admin-only, audited).

Use this for: an emergency stop (compromised question content, vendor
incident). Do **not** use this to "give one candidate extra time" — that
is a per-attempt extension, not an assessment-level action.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.assessments.invite.bulk',
  'admin',
  'en',
  'Paste up to 500 emails (one per line). Existing users are linked; new users get a magic-link signup.',
  $$## Bulk invite

Paste up to 500 candidate emails — one per line. AssessIQ:

1. **De-duplicates** within the input list and against existing
   invitations on this assessment.
2. **Links existing users** by email. They receive a sign-in invitation
   only.
3. **Creates pending users** for new emails. They receive a magic-link
   sign-up + assessment invitation in one email.

**Rate-limited:** 500 emails per hour per tenant per admin. The UI shows
a progress bar; if you hit the limit, the remaining emails queue and send
over the next hour automatically.

**Email content:** uses the tenant's branded template if configured, the
default template otherwise. Editing templates is an admin-settings page.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'candidate.intro.integrity',
  'candidate',
  'en',
  'AssessIQ measures judgment and reasoning, not memory. Use any reference you would in a real workday.',
  $$## Integrity expectations

This assessment is not a closed-book exam. AssessIQ is built to measure
how you think on the job, not what you can recall under pressure. Use:

- **Documentation** for the tools and languages you would normally
  reference at work.
- **Search engines** to look up syntax or operators.
- **Notes** you would normally have open.

Do **not** ask another person to answer for you, share screens, or paste
answers from another candidate's attempt. AssessIQ records timing
signals, edit patterns, and behavioral fingerprints; identical or
near-identical answers across candidates are flagged for review.

Once you click **Begin Assessment**, the timer starts and cannot be
paused. If your network drops, your answers are saved every 5 seconds —
you can refresh and continue.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'candidate.attempt.timer',
  'candidate',
  'en',
  'Wall-clock time remaining. Auto-submits at zero. Pausing is not supported.',
  $$## Timer

The countdown shows time remaining for the entire assessment, not the
current question. When it reaches zero, AssessIQ auto-submits whatever
answers you have entered.

**The timer keeps running even if you close the tab.** Network dropouts
do not pause it. If you genuinely cannot continue (power outage,
medical emergency), close the tab and contact your administrator
immediately — they can grant a one-time extension before submission.

Behavioral signals recorded by AssessIQ include time spent per question,
number of edits, and navigation pattern. None of these signals affect
your score directly; they inform the admin's review.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'candidate.attempt.flag',
  'candidate',
  'en',
  'Bookmark the question to revisit before final submit. Flags have no scoring impact.',
  $$## Flag for review

Use this when you want to come back to a question before final submission —
for instance, if you are not sure of your answer or want to verify a query.

Flagged questions appear with a star in the navigation panel. You can flag
multiple questions; the **Review** screen lists all flagged + unanswered
items together so you do not miss anything.

Flagging has no scoring impact. It is just a personal bookmark.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'candidate.attempt.kql.editor',
  'candidate',
  'en',
  'Write your KQL query. Syntax highlighting + autocomplete. Press Ctrl+Enter to validate.',
  $$## KQL editor

The editor offers:

- **Syntax highlighting** for KQL keywords, operators, and built-in
  functions.
- **Autocomplete** for table names referenced in the question scenario.
- **Bracket / paren matching** to spot mismatches early.
- **Format on save** (Ctrl+Shift+F) — opinionated, optional.

**Validation** (Ctrl+Enter) checks for:

- Parse errors (red underline).
- Required keyword presence — the question lists tokens that must appear
  somewhere in your query for it to score above band 0.

Validation does not run your query against real data. The grader judges
correctness by combining keyword presence with AI rubric review.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'candidate.attempt.scenario.steps',
  'candidate',
  'en',
  'Multi-step incident. Some steps may unlock only after submitting earlier steps.',
  $$## Scenario steps

Scenario questions describe a developing incident across multiple steps.
Each step asks for a decision or analysis given the evidence so far.

**Two modes:**

- **Free navigation** (default): jump between steps freely. You may
  revise earlier steps as later evidence arrives.
- **Locked progression**: each step unlocks only after you submit the
  previous one. Look for a small lock icon on later steps.

Once you submit a step in locked mode, you cannot edit it. In free mode
every step stays editable until you submit the assessment.

Behavioral note: AssessIQ records the order you visited the steps. There
is no "correct" order — exploring later evidence first is a valid
strategy.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'candidate.attempt.subjective.length',
  'candidate',
  'en',
  'Recommended 80–200 words per answer. Quality of reasoning beats word count.',
  $$## Subjective answer length

Subjective questions are graded on the rubric (anchors and bands), not on
length. A 60-word answer that nails the tradeoff scores higher than a
300-word answer that meanders.

**Rough guide:**

- **Below 40 words:** rarely enough to demonstrate reasoning.
- **80–200 words:** the sweet spot for most rubrics.
- **Above 300 words:** law of diminishing returns; you are using time
  that other questions need.

Markdown formatting (bullets, **bold**, `code`) renders in the grader's
review. Use it when it clarifies; do not use it as filler.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'candidate.attempt.disconnect',
  'candidate',
  'en',
  'Your answers autosave every 5 seconds. Refresh and continue — the timer keeps running.',
  $$## If your connection drops

AssessIQ saves your in-progress answers to the server every 5 seconds and
shows a small green check next to "Saved" when the latest save completed.
A red dot means the last save attempt failed; AssessIQ will retry on the
next interval.

**If you lose connectivity:**

1. **The timer keeps running** — wall-clock time, not connected time.
2. **Reconnect and refresh** — your most recent autosaved state loads.
3. **Anything typed during the offline window is lost** — only saved
   state survives a refresh.

For a genuinely-blocking outage (power, hardware failure), close the tab
and contact your administrator. They can grant a one-time extension
before final submission, but cannot extend after auto-submit fires.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'candidate.attempt.submit.confirm',
  'candidate',
  'en',
  'Once submitted, you cannot reopen the attempt. Verify your flagged questions first.',
  $$## Submitting your attempt

Submission is **final**. AssessIQ does not allow editing answers after
submit, and there is no second attempt unless your administrator
explicitly grants one.

Before clicking the final **Submit** button, the **Review** screen shows:

- Flagged questions you wanted to revisit.
- Unanswered questions (a blank textarea or empty MCQ counts).
- Questions whose autosave is stale (rare — usually only seconds old).

Walk through any starred or unanswered items. When you are ready, click
**Submit**. AssessIQ confirms submission with a final dialog and the
candidate timer freezes immediately.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'candidate.submit.confirm',
  'candidate',
  'en',
  'Final confirmation — clicking Submit ends the attempt and starts the grading queue.',
  $$## Final submit dialog

This dialog is the last step. Once you confirm, AssessIQ:

1. Freezes your answers and the timer.
2. Records all behavioral signals.
3. Queues the attempt for grading.
4. Emails your administrator that the attempt is ready for review.

**You will not see your score immediately.** AI grading runs synchronously
when an admin opens your attempt for review (Phase 1). Your administrator
will email you once the score is released; depending on their workflow,
that can be the same day or several days later.

There is no "save and continue later" option from this dialog — once you
are here, you have committed to submitting.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'candidate.result.bands',
  'candidate',
  'en',
  'Bands 0/25/50/75/100 represent your performance vs the rubric, not a raw percentage.',
  $$## Understanding your score

AssessIQ does not report raw percentages for subjective and scenario
questions. Instead, every answer lands on a **band**:

| Band | Meaning |
|---|---|
| **0** | Missing, off-topic, or fundamentally incorrect |
| **25** | Touched the right area but missed the key point |
| **50** | Partial credit — covered some of the rubric, missed the rest |
| **75** | Substantially correct, with one notable gap |
| **100** | Complete and well-reasoned per the rubric anchors |

**Why bands and not percentages?** Subjective work is not millimetric.
Two graders comparing "73% vs 76%" learn nothing useful; comparing band
50 vs band 75 forces a clear judgement call. AssessIQ surfaces the AI's
band, the AI's justification, and any admin override side-by-side — so
your record is transparent end-to-end.

MCQ and KQL questions also map to bands so the final score has a
consistent shape.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;
