-- generated by tools/generate-help-seed.ts on 2026-05-03T14:25:45.799Z
-- DO NOT EDIT BY HAND. Re-run the generator after editing YAML:
--   pnpm tsx tools/generate-help-seed.ts
--
-- Idempotency: ON CONFLICT (tenant_id, key, locale, version) DO NOTHING
-- means re-running this migration after a YAML edit does not change v1
-- rows already seeded. To update content, use the upsertHelp service
-- (which bumps version). Global rows (tenant_id IS NULL) are inserted as
-- the postgres superuser which BYPASSes RLS — the app role cannot insert
-- global rows per the INSERT policy on help_content.

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.auth.login.tenant_slug',
  'admin',
  'en',
  'Your organization''s slug — the unique URL-safe ID we issued during onboarding (e.g. wipro-soc).',
  $$## Tenant slug

Each AssessIQ tenant has a short, URL-safe identifier you'll use at every
sign-in. It usually mirrors your team or product name (e.g. `wipro-soc`,
`acme-secops`). Your AssessIQ administrator received the slug at onboarding;
if you don't have it, ask them — it is not the same as your email domain.

The slug is also used in webhook payloads and embed-iframe URLs, so once it
is set it stays stable. Renaming a tenant is a manual operation that
requires support.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.auth.mfa.enroll_vs_verify',
  'admin',
  'en',
  'First-time admins enroll an authenticator app here; returning admins enter their 6-digit code to sign in.',
  $$## TOTP enrollment vs verification

The first time an admin signs in, AssessIQ shows a QR code and asks you to
scan it with an authenticator app (Google Authenticator, Authy, 1Password,
Microsoft Authenticator). After scanning, enter the 6-digit code shown in
the app to confirm the secret matches.

Returning admins skip the QR code and only enter the 6-digit code. Codes
rotate every 30 seconds; AssessIQ accepts the previous, current, and next
code to absorb small clock drifts.

Lockout policy: five wrong codes in a row locks the account for 15 minutes.
Recovery codes are not yet supported in Phase 1 — if you lose access,
another admin must reset your TOTP enrollment.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.users.role',
  'admin',
  'en',
  'admin = full access · reviewer = grade and override only · candidate = take assessments only.',
  $$## User roles

| Role | Can do |
|---|---|
| **admin** | Everything: tenant settings, packs, assessments, grading, exports, billing |
| **reviewer** | Grade and override AI verdicts; view assessment results; cannot edit packs or invite users |
| **candidate** | Take assigned assessments; view their own past scores |

Role changes take effect on the next sign-in for that user. Demoting an
admin to reviewer revokes their fresh-MFA gates immediately. There is no
"owner" or "billing" role — that is a Phase 2 concern.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.packs.create.domain',
  'admin',
  'en',
  'The role-readiness domain this pack covers (SOC analyst, DevOps, etc.). Set once; choose carefully.',
  $$## Pack domain

A *pack* is a collection of leveled questions for a single role-readiness
domain. The domain is metadata only — AssessIQ has no domain-specific
code paths — but it controls the default rubric anchors, the example UI
copy, and how packs sort in the admin browser.

Common values: `soc-analyst`, `devops-engineer`, `cloud-architect`,
`identity-engineer`, `incident-responder`. Use lowercase, dash-separated.

You cannot rename a pack's domain after questions exist under it — clone
the pack into a new domain instead.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.questions.generate.draft',
  'admin',
  'en',
  'AI-assisted question drafts are a Phase 2 feature; for now, author by hand or import from JSON.',
  $$## AI-assisted question generation

Phase 2 will add a **Generate draft** button that takes a one-line prompt
("design a tier-2 SOC scenario about phishing escalation") and returns a
fully-shaped question with anchors, rubric bands, and example responses,
using the same AI-grading pipeline that scores attempts.

For Phase 1 you have two paths:

1. **Author by hand** — fill the question form (type, body, expected
   answers, rubric) directly.
2. **Import JSON** — paste or upload a JSON document conforming to the
   schema in `modules/04-question-bank/import.schema.json`.

The hand-authored path supports every question type the engine understands;
JSON import is convenient for migrating from spreadsheets.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.questions.import.format',
  'admin',
  'en',
  'JSON only in Phase 1 (CSV is Phase 2). Schema: modules/04-question-bank/import.schema.json.',
  $$## Question import format

Bulk import accepts a single JSON document in this Phase. The document
schema is published at
`modules/04-question-bank/import.schema.json`; in summary:

```jsonc
{
  "pack": "soc-analyst-v1",
  "level": "L2",
  "questions": [
    {
      "type": "mcq | kql | scenario | subjective",
      "body": "...",
      "answers": [...],          // shape varies by type
      "rubric": { ... },         // for subjective / scenario
      "tags": ["phishing", "triage"]
    }
  ]
}
```

CSV import is on the Phase 2 roadmap. Until then, convert spreadsheets to
JSON with a script of your choice — the schema is plain enough to template.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.questions.type.kql.expected_keywords',
  'admin',
  'en',
  'Tokens that MUST appear (case-insensitive) for the answer to score above band 0. Add 1–5 per question.',
  $$## KQL expected keywords

KQL questions are graded on a hybrid: **deterministic keyword presence**
plus AI judgement on syntactic and semantic correctness. The keyword list
is the deterministic floor — if none of the listed tokens appear in the
candidate's query, the answer can score at most band 0 regardless of how
elegant the rest of the query is.

**Recommendations:**

- Pick tokens that are *necessary*, not sufficient: a query that lacks
  `where` or the target table cannot be correct.
- 1–5 keywords per question. More than 5 makes scoring brittle.
- Use case-insensitive matching (`Where`, `where`, `WHERE` all match).
- Quoted identifiers (`"My Table"`) are matched literally; bare tokens
  are matched as whole words (`time` will not match `timestamp`).

The AI grader sees the keyword list as a hint and uses it to anchor its
own judgement — admin can still override.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.questions.type.scenario.step_dependency',
  'admin',
  'en',
  'Lock a step so it can''t be answered until the previous step is submitted. Use sparingly.',
  $$## Step dependency

Scenario questions present a multi-step incident. By default, candidates
can navigate freely — they may answer step 3 before step 1 if they want
to think non-linearly. Setting **step dependency** locks each step until
the previous one is submitted.

**When to enable:**

- The branching narrative (we tell the candidate "the alert escalated
  because…") would spoil the answer to an earlier step.
- You want to measure pure decision speed without back-tracking.

**When not to:**

- Standard triage workflows. Real analysts revisit earlier conclusions.
- Investigation-style scenarios where evidence accumulates.

The candidate sees a small lock icon on dependent steps and a clear
"Submit step N to continue" prompt.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.questions.type.subjective.rubric',
  'admin',
  'en',
  'Anchors describe each band (0/25/50/75/100). Write band 100 first, then 0, then fill the middle.',
  $$## Subjective rubric anchors

AI grading uses the rubric anchors as the *one* shared truth between the
AI's judgement and your override. Every grading record stores the anchors
that were active at grade time, so an audit trail survives even if you
later refine the rubric.

**Authoring approach that works:**

1. Write **band 100** first — what does an obviously correct, complete
   answer look like? Be specific: which terms, structures, or tradeoffs
   must appear.
2. Write **band 0** second — what is missing, vague, or wrong enough to
   score zero? The AI uses this as the negative anchor.
3. Fill **band 50** — the middle: partial credit, missing one of two
   required elements, correct intuition with weak rationale.
4. Fill **band 25** and **band 75** by interpolation.

**Anti-patterns:**

- "It depends" or "looks reasonable" — too vague for the AI to ground on.
- Numeric thresholds the AI can't verify (e.g. "discusses at least three
  mitigations" works; "scores 7/10 on accuracy" doesn't).
- More than ~80 words per band — the rubric is a contract, not an essay.

Override the AI verdict any time. Your override sits *beside* the AI's
record, never replaces it.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.assessments.create.duration',
  'admin',
  'en',
  'Total wall-clock minutes from candidate start to auto-submit. L1: 30–45, L2: 45–60, L3: 60–90.',
  $$## Duration

The total time a candidate has from clicking **Begin Assessment** to the
auto-submit. Once started, the timer cannot be paused.

**Recommendations:**

- **L1 / triage-style:** 30–45 minutes
- **L2 / investigation:** 45–60 minutes
- **L3 / detection engineering:** 60–90 minutes

Candidates can navigate freely between questions during this window.
Auto-submit fires the moment the timer hits zero — partial answers are
saved.

> **Note:** Time-based behavioral signals (per-question time spent, edits)
> are captured regardless of duration. Do not compress duration to "force
> speed"; the platform measures speed separately.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.assessments.create.question_count',
  'admin',
  'en',
  'How many questions to draw from the pack/level pool. Must be ≤ active questions in the pool.',
  $$## Question count

AssessIQ samples this many questions from the pack + level you chose. If
randomization is on, every candidate sees a different draw; if off, all
candidates see the same set in the same order.

**Constraints:**

- Must be ≤ the number of `active` questions in the pool. Publish fails
  if not.
- Pool size is shown live next to this input as you author.
- Recommended ratio: ~1 question per 4 minutes of duration. Higher density
  is fine for MCQ-heavy assessments; lower for scenario or subjective
  heavy ones.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.assessments.create.randomize',
  'admin',
  'en',
  'Each candidate sees a different sample + order. Off = identical assessment for everyone.',
  $$## Randomize question selection

With randomization on, every candidate's attempt:

- Draws a fresh sample from the pool (size = question count).
- Shuffles question order.
- Shuffles MCQ answer order on a per-question basis.

The seed is stable per attempt, so refreshing the page does not re-shuffle.

**When to turn it off:**

- Calibrating a new pack against a fixed reference set.
- Live training events where everyone sees the same screen.
- Anti-cheat is **not** the right reason — randomization is not a
  meaningful integrity control. Use real-time monitoring or proctoring
  tools instead.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.assessments.publish',
  'admin',
  'en',
  'Locks the question set, opens invitations, and starts the schedule. Pre-flight checks run automatically.',
  $$## Publish assessment

Publishing flips the assessment from `draft` to `published` and runs three
pre-flight checks:

1. **Pool size** — the active question pool ≥ the requested question
   count.
2. **Open window** — `opens_at` is in the future or already past with a
   valid `closes_at`.
3. **Notification config** — if invitations are scheduled, the tenant has
   a working SMTP config.

Once published, the question set is **frozen** for that assessment. Edits
to questions in the underlying pack do not affect already-published
assessments — that is by design (HR auditability).

To change a published assessment, **close** it and create a new one.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.assessments.close.early',
  'admin',
  'en',
  'Sends auto-submit to every in-progress attempt. Cannot be undone — closes the schedule immediately.',
  $$## Close assessment early

Forces the assessment from `active` to `closed` immediately, regardless of
`closes_at`. Effects:

- Every in-progress attempt is auto-submitted with whatever answers exist.
- Pending invitations are revoked; their links return a "this assessment
  is closed" page if used.
- Notifications fire as if the schedule had ended naturally.

**You cannot reopen** a closed assessment whose `closes_at` has passed.
Re-opening before `closes_at` is allowed but rare — see
`assessment.reopen` (admin-only, audited).

Use this for: an emergency stop (compromised question content, vendor
incident). Do **not** use this to "give one candidate extra time" — that
is a per-attempt extension, not an assessment-level action.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.assessments.invite.bulk',
  'admin',
  'en',
  'Paste up to 500 emails (one per line). Existing users are linked; new users get a magic-link signup.',
  $$## Bulk invite

Paste up to 500 candidate emails — one per line. AssessIQ:

1. **De-duplicates** within the input list and against existing
   invitations on this assessment.
2. **Links existing users** by email. They receive a sign-in invitation
   only.
3. **Creates pending users** for new emails. They receive a magic-link
   sign-up + assessment invitation in one email.

**Rate-limited:** 500 emails per hour per tenant per admin. The UI shows
a progress bar; if you hit the limit, the remaining emails queue and send
over the next hour automatically.

**Email content:** uses the tenant's branded template if configured, the
default template otherwise. Editing templates is an admin-settings page.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.reports.cohort.distribution',
  'admin',
  'en',
  'Archetype distribution shows how many submitted attempts landed in each performance archetype for this assessment.',
  $$## Cohort archetype distribution

AssessIQ classifies each completed attempt into one of five archetypes:

| Archetype | Meaning |
|---|---|
| `confident_correct` | High score with consistent reasoning alignment |
| `capable_but_unsure` | High score but lower reasoning quality |
| `memorised_pattern` | Correct answers without analytical depth |
| `partial_grasp` | Mixed accuracy; some topics understood |
| `needs_support` | Low score, reasoning gaps across topics |

The distribution chart reflects **submitted and scored** attempts only.
In-progress or pending-review attempts are excluded until grading is complete.

Archetypes are immutable once assigned — reassessing a candidate creates a
new attempt with its own archetype.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.reports.heatmap.colors',
  'admin',
  'en',
  'Heat cell color = average reasoning band for that topic-level pair: green (3–4), amber (2), red (0–1).',
  $$## Topic heatmap color scale

Each cell in the topic heatmap represents one topic × level combination.
The color encodes the mean **reasoning band** (0–4) of all graded questions
in that cell:

| Color | Band range | Interpretation |
|---|---|---|
| Green | 3–4 | Strong reasoning; candidates consistently explained the concept |
| Amber | 2 | Partial reasoning; correct answers but shallow justification |
| Red | 0–1 | Weak reasoning; frequent guessing or pattern-matching |

A cell shows as **grey** when fewer than two attempts have graded answers
for that topic — not enough data to draw a meaningful conclusion.

The **hit rate** (right side of each cell) is the fraction of questions in
that cell answered correctly, regardless of reasoning band.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.reports.archetype.disclaimer',
  'admin',
  'en',
  'Archetypes are statistical descriptors, not diagnostic labels. Use them to guide learning — not hiring decisions.',
  $$## Archetype disclaimer

AssessIQ archetypes are computed by an AI rubric engine that scores
reasoning quality on a 0–4 band scale. They are designed to identify
**learning gaps and strengths at scale**, not to serve as a definitive
measure of individual ability.

**Do not use archetypes as the sole basis for hiring, promotion, or
compensation decisions.** They are complementary signals to human
review, structured interviews, and on-the-job evaluation.

Archetype accuracy depends on:
- Question prompt quality (well-scoped rubric anchors improve band accuracy)
- Attempt length (short assessments yield less signal)
- Current AI pipeline mode (`claude-code-vps` uses deterministic scoring;
  `anthropic-api` uses LLM-based reasoning-band scoring)

Results should be reviewed alongside raw scores and grading transcripts.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.reports.export.format',
  'admin',
  'en',
  'Exports are available as CSV (Excel-compatible) or JSONL (one JSON object per line, for pipeline ingest).',
  $$## Export formats

**CSV (`attempts.csv`)** — one row per scored attempt. Compatible with
Excel, Google Sheets, and most BI tools. Columns:

`tenant_id`, `assessment_id`, `assessment_name`, `user_id`, `user_email`,
`attempt_id`, `status`, `submitted_at`, `total_earned`, `total_max`,
`auto_pct`, `archetype`, `computed_at`

**JSONL (`attempts.jsonl`)** — one JSON object per line. Use this for
scripted pipeline ingest or when you need to preserve numeric precision.
Each object has the same fields as the CSV.

**Topic heatmap CSV (`topic-heatmap.csv`)** — one row per topic × level
combination. Columns: `pack_id`, `level_id`, `topic`, `hit_rate`,
`mean_band`, `attempt_count`.

**Row cap:** all export endpoints are capped at 10,000 rows. If your
tenant has more data, use the `submittedAfter` / `submittedBefore`
filters to export in date-range batches.

**Audit:** every export is logged in the audit trail with the acting
admin's user ID and a timestamp.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.reports.cost.empty_in_claude_code_vps_mode',
  'admin',
  'en',
  'Cost breakdown requires anthropic-api mode. This deployment uses claude-code-vps — no per-call cost is metered.',
  $$## Grading cost breakdown — not available in VPS mode

The cost-by-month report tracks Anthropic API token spend per assessment.
It is populated when `AI_PIPELINE_MODE=anthropic-api` is active.

This deployment uses `claude-code-vps` mode: a human-operated Claude Code
session runs the grading workflow on the VPS, and token costs are not
metered through the AssessIQ billing system.

If you switch to `anthropic-api` mode in a future deployment, the cost
report will begin populating from that date forward.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.audit.export.format',
  'admin',
  'en',
  'The audit log records admin actions (exports, grading, user changes) with actor, timestamp, and tenant scope.',
  $$## Audit log

AssessIQ maintains an append-only audit log for every significant admin
action. Entries are written synchronously with the operation (not
fire-and-forget) to guarantee no silent loss.

**Audited actions include:**
- `attempt.exported` — admin downloaded a CSV or JSONL export
- `grading.override` — admin manually changed a grading band
- `user.created`, `user.role_changed`, `user.deactivated`
- `assessment.published`, `assessment.archived`
- `pack.version_bumped`

Audit log entries are immutable. They cannot be edited or deleted by any
admin — including tenant super-admins. Retention is 7 years (configurable
by the platform operator).

The export audit entry includes `export_format` and the filter parameters
used, so the exact dataset exported can be reconstructed.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.audit.archives.restore_procedure',
  'admin',
  'en',
  'Archived assessments are soft-deleted. Contact your platform admin to restore — no self-service restore in Phase 3.',
  $$## Restoring archived assessments

Archiving an assessment sets its status to `archived` and hides it from
the active assessments list. The underlying data (attempts, gradings,
scores) is fully preserved.

**To restore** in the current Phase 3 build:

1. Contact your AssessIQ platform administrator.
2. Provide the assessment ID (visible in the audit log entry for the
   archive action).
3. The admin updates `status = 'active'` and re-enables any active
   invite links.

Self-service restore via the UI is planned for Phase 4.

**Grading data:** attempts submitted before archiving retain their scores
and archetype assignments. No re-grading is triggered on restore.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.notifications.in_app.short_poll_interval',
  'admin',
  'en',
  'In-app notifications are fetched every 15 seconds. There is no WebSocket push in Phase 3.',
  $$## In-app notification polling

The admin dashboard polls for new in-app notifications every **15 seconds**
using a short-poll strategy. Notifications include:

- Grading complete (an attempt's AI grading finished)
- Bulk invite batch complete (all emails sent)
- Assessment boundary transitions (e.g. attempt timer expired)

**Why short-poll?** Phase 3 does not include a WebSocket server. Short
polling over HTTPS is simpler to operate and sufficient for the current
notification volume (< 10 tenants, < 100 concurrent admins).

**Phase 4** will evaluate WebSocket or SSE push once the candidate UI
(module 11) ships and real-time status updates become time-critical.

If a notification arrives between polls, it will appear at the next tick.
The 15-second window is intentional — it avoids overloading the DB with
sub-second polling while keeping the perceived lag minimal for admin-level
workflows.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.grading.queue.row',
  'admin',
  'en',
  'Each row is an attempt awaiting review. Click ''Review'' to open the grading panel.',
  $$## Grading queue row

A row appears here when a candidate submits an attempt containing at least
one subjective or scenario question. Clicking **Review** opens the attempt
detail page, which simultaneously claims the attempt (`submitted →
pending_admin_grading`) so other admins know you are reviewing it.

The claim is soft: if you navigate away without grading, the attempt
reverts to `submitted` on the next queue refresh.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.grading.queue.empty',
  'admin',
  'en',
  'No attempts awaiting grading. Either no assessments have run yet, or all attempts are already graded.',
  $$## Empty grading queue

The queue is empty when all submitted attempts have been graded and released,
or when no assessments have had any submissions yet.

If you expected to see something here, check:
- The **Attempts** page with filter "All" — the attempt may already be
  in `graded` or `released` status.
- Whether the assessment has expired or closed before candidates submitted.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.grading.proposal.anchors',
  'admin',
  'en',
  'Green chips = anchor phrases the AI found; grey chips = anchors it didn''t detect.',
  $$## Anchor findings

Each anchor in the rubric is shown as a chip. **Green / hit** means the AI
found the concept in the candidate's answer (with evidence shown on hover).
**Grey / miss** means the concept was absent or the AI was not confident
enough to flag it.

Misses do not automatically reduce the score — band scoring is holistic.
A band-3 answer can miss a minor anchor if the overall reasoning quality
justifies it. Use the anchor display as a *starting point*, not a checklist.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.grading.proposal.band',
  'admin',
  'en',
  'The AI''s verdict on reasoning quality: 0 = no credit, 1 = 25%, 2 = 50%, 3 = 75%, 4 = 100%.',
  $$## Reasoning band

Bands map to percentage scores: **0 → 0%, 1 → 25%, 2 → 50%, 3 → 75%,
4 → 100%**. Raw floats are never surfaced — only these five values.

The band represents the AI's holistic judgement of the candidate's
reasoning quality, not a count of correct facts. A response that correctly
identifies the right tool but fails to explain *why* it is right typically
lands at band 2–3, not 4.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.grading.proposal.justification',
  'admin',
  'en',
  'The AI''s free-text reasoning for its band choice. Read before accepting or overriding.',
  $$## AI justification

The AI grader writes a short explanation of why it chose the verdict it did.
Read this before clicking Accept — it surfaces the evidence and reasoning
that drove the band choice.

If the justification is vague ("the answer is mostly correct"), that is a
signal to run Stage 3 (Opus re-run) before accepting.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.grading.proposal.error_class',
  'admin',
  'en',
  'The error type if band < 3: missing_concept, wrong_tool, wrong_reasoning, partial_answer, or none.',
  $$## Error class

When the AI assigns band 0–2, it also assigns an error class:

| Class | Meaning |
|---|---|
| `missing_concept` | Core concept absent from the answer |
| `wrong_tool` | Candidate chose the wrong tool or approach |
| `wrong_reasoning` | Tool is right but the explanation is incorrect |
| `partial_answer` | Correct direction, incomplete execution |
| `none` | No specific error class (band 3–4) |

Error classes feed the cohort-level analytics (which error types are
most common) and the archetype signal computation.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.grading.proposal.escalation',
  'admin',
  'en',
  'Stage-3 (Opus) re-run differs from Stage-2 (Sonnet) by ≥2 bands. Pick the verdict to keep.',
  $$## Escalation diff

When you click **Re-run with Opus**, Stage 3 grades the answer
independently using a more powerful model. If the verdicts differ by 2 or
more bands (e.g. Sonnet said band 2, Opus says band 4), the escalation diff
appears side-by-side.

You must pick one verdict and write a reconciliation note before submitting.
The chosen stage is recorded on the `gradings` row so future analysis can
identify systematic AI disagreements.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.grading.accept',
  'admin',
  'en',
  'Accept commits the AI''s proposal to the gradings table. No fresh MFA required.',
  $$## Accept AI proposal

Clicking Accept:

1. Writes the AI's band, score, anchor hits, and justification to the
   `gradings` table with `grader = 'ai'`.
2. Does **not** release the attempt to the candidate — release is a
   separate action once all questions are graded.

Accept does not require fresh MFA. Override does.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.grading.override.reason',
  'admin',
  'en',
  'Required when overriding the AI. Shown in audit exports and used for AI calibration feedback.',
  $$## Override reason

The override reason is mandatory and must be meaningful — it feeds:

- The **audit trail** for HR and compliance exports.
- Future AI calibration: patterns in override reasons help identify rubric
  gaps or systematic AI errors.

Minimum useful length: one sentence describing *what was wrong* with the
AI's verdict. "Wrong band" alone fails validation.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.grading.rerun',
  'admin',
  'en',
  'Re-run asks the AI to grade the same answer again with Sonnet. Use when the initial proposal looks wrong.',
  $$## Re-run (Sonnet)

Re-run submits the same answer and rubric to Stage 2 (Sonnet) again.
Because AI grading is non-deterministic, a second pass sometimes produces
a better proposal, especially for ambiguous answers.

Use re-run when:
- The justification is clearly misaligned with the rubric.
- The anchor hits don't match what you read in the answer.
- The band seems too high or too low but you want a second opinion before
  overriding manually.

Re-run does **not** replace the original proposal — both are in the
`gradings` table (with `override_of` linking them).
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.grading.rerun.opus',
  'admin',
  'en',
  'Re-run with Opus (Stage 3) uses a more powerful model. Use for complex cases or appeals.',
  $$## Re-run with Opus (Stage 3)

Stage 3 uses Claude Opus — a more capable but slower model. Use it for:

- Complex multi-step scenario answers where Sonnet's chain-of-thought
  seems shallow.
- Appeals: the candidate disputes the grade and you want an independent
  high-quality re-assessment.
- Calibration: spot-check whether Stage 2 verdicts hold up on a sample
  of high-stakes attempts.

Stage 3 is billed at a higher token cost. The tenant budget guard tracks
and may block if the monthly cap is near.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.grading.skill_drift',
  'admin',
  'en',
  'The prompt version used for this grade differs from the current live prompt. Consider re-grading.',
  $$## Skill drift

Each grading row records the SHA-256 hash of the prompt version that
produced it. If the admin updates a grading skill (prompt template), rows
graded with the old version are flagged with a **drift** badge.

Drift is informational — it does not block releasing results. Use it as a
signal to re-run affected attempts when a prompt change was material (e.g.
a rubric anchor was corrected).
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.scoring.attempt.total',
  'admin',
  'en',
  'Sum of earned points across all questions, normalized to 100. Bands are shown per-question only.',
  $$## Total score

The attempt total is a weighted sum of per-question scores, normalized to
100. It is derived from the `attempt_scores` row written when all questions
are graded.

For subjective questions, the per-question score is `reasoning_band × 25`,
so a band-3 answer on a 20-point question contributes 15 points.

The total does **not** drive pass/fail thresholds directly — the archetype
and cohort percentile are also factors. See `admin.scoring.cohort.percentiles`.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.scoring.attempt.archetype',
  'admin',
  'en',
  'Behavioral pattern derived from edit count, pace, flags, multi-tab, and copy-paste signals.',
  $$## Archetype signals

The archetype radar charts six behavioral signals collected during the attempt:

| Signal | Measures |
|---|---|
| Pace | Median time per question |
| Edits | Total edit count across answers |
| Flags | Questions flagged for review |
| Focus loss | Tab-blur events |
| Copy/paste | Combined copy + paste events |
| Multi-tab | Multi-tab conflict events |

High edit counts combined with slow pace may indicate careful, deliberate
work. High copy/paste with fast pace may indicate pasted content. Context
matters — interpret signals holistically, not as individual scores.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.scoring.archetype.disclaimer',
  'admin',
  'en',
  'Behavioral signals are observational only. They do not affect the score and are not a proxy for integrity.',
  $$## Archetype signal disclaimer

Archetype signals are behavioral telemetry, not integrity flags. They:

- Do **not** adjust the candidate's score in any direction.
- Are **not** a proxy for cheating detection.
- Are context-dependent: a slow pace on L3 scenarios is normal; the same
  pace on an L1 triage question might indicate difficulty.

Use signals to understand cohort patterns (e.g. "L2 candidates average
200 edits per attempt") not to make individual pass/fail decisions.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.scoring.cohort.percentiles',
  'admin',
  'en',
  'Rank within the cohort. 90th percentile = scored higher than 90% of candidates on the same assessment.',
  $$## Cohort percentiles

Cohort percentiles are computed once the cohort has ≥5 released results.
They are recomputed on every new release.

A candidate at the 90th percentile scored higher than 90% of the cohort
on the same assessment + level. Percentiles are assessment-scoped — they
do not span across assessments or levels.

Phase 1 computes median and percentile bands (P25, P50, P75, P90). Full
bell-curve distribution charts are a Phase 3 analytics feature.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.scoring.leaderboard.privacy',
  'admin',
  'en',
  'Anonymize toggle hides candidate emails. Leaderboard data is admin-only and never shown to candidates.',
  $$## Leaderboard privacy

The cohort leaderboard is visible to admins and reviewers only — candidates
never see their rank or peers' scores.

Use the **Anonymize** toggle to hide email addresses when screensharing
or presenting cohort results to stakeholders. The setting is stored in your
browser session only (not tenant-wide).
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.rubric.anchor.weight',
  'admin',
  'en',
  'Fractional contribution of this anchor to the total rubric weight. All anchor weights must sum ≤ 1.0.',
  $$## Anchor weight

The weight controls how much this anchor contributes to the overall
scoring floor. All anchor weights must sum to ≤ 1.0 (the UI shows the
running total and blocks saving if exceeded).

Recommended allocation: identify 2–4 *essential* anchors (weight 0.2–0.3
each) and 2–4 *supporting* anchors (weight 0.05–0.1 each). Leave room in
the total so a strong answer that covers most anchors isn't penalized by
one missed nuance.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.rubric.anchor.synonyms',
  'admin',
  'en',
  'Comma-separated synonyms or equivalent phrasings the AI should treat as matching the anchor.',
  $$## Anchor synonyms

Add synonyms when the anchor concept has multiple correct phrasings.
Example: anchor phrase "lateral movement", synonyms "east-west traffic,
network pivoting, pivot host".

Synonyms are case-insensitive and matched as substrings within the answer.
Avoid overly broad synonyms that could match unrelated content.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.rubric.anchor.required',
  'admin',
  'en',
  'Required anchors must be present for the answer to score above band 0, regardless of overall quality.',
  $$## Required anchor

Marking an anchor **required** creates a hard floor: if the AI does not
detect this concept, the band is capped at 0 regardless of the rest of
the answer quality.

Use sparingly — for concepts so fundamental that their absence represents
a complete misunderstanding. For most anchors, leave required off and let
the holistic band judgement do its work.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.rubric.reasoning.bands',
  'admin',
  'en',
  'Band labels and descriptions tell the AI how to distinguish between 0%, 25%, 50%, 75%, and 100%.',
  $$## Reasoning bands

Write a label and description for each of the five bands. These are
included verbatim in the AI grading prompt — they are the specification
the model grades against.

Best practice:
- **Band 4 (100%):** Complete, accurate, specific. Names tools, explains
  tradeoffs, shows system-level reasoning.
- **Band 3 (75%):** Mostly correct. One missing element or weak rationale.
- **Band 2 (50%):** Correct direction, significant gaps. Explains *what*
  but not *why*, or vice versa.
- **Band 1 (25%):** Shows partial understanding. More wrong than right.
- **Band 0 (0%):** No credit. Blank, off-topic, or fundamentally wrong.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.rubric.error_classes',
  'admin',
  'en',
  'Error classes tag low-band answers for cohort analytics. Choose the one that best describes the failure.',
  $$## Error classes

Error classes are assigned by the AI when band < 3 and aggregated in the
cohort analytics view. They answer: "what kind of mistake did candidates
make most often on this question?"

Available classes:
- `missing_concept` — the core concept was absent
- `wrong_tool` — candidate chose the wrong approach
- `wrong_reasoning` — reasoning is incorrect despite using the right tool
- `partial_answer` — correct direction, incomplete

Admin overrides can also set the error class. If no class applies, leave
as `none`.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.settings.billing.budget',
  'admin',
  'en',
  'Monthly grading run cap per tenant. Default: 100 runs/month. Resets on the 1st of each month.',
  $$## Grading budget cap

The budget guard limits AI grading runs to protect against runaway costs.
A "run" is one call to the grading pipeline per question — a 10-question
attempt uses 10 runs.

Default cap: 100 runs/month per tenant. Contact support to raise the cap.
The `tenant_grading_budgets` table holds the current usage and cap; a
platform admin can edit it directly until Phase 3 ships a settings UI.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.settings.billing.alert_threshold',
  'admin',
  'en',
  'Notify the admin when monthly usage exceeds this percentage of the cap (default: 80%).',
  $$## Budget alert threshold

When monthly grading usage crosses this fraction of the cap, AssessIQ sends
an in-app notification and email to all tenant admins. Default: 80%.

The notification is informational — grading continues until the hard cap
is hit. Raise the cap in `tenant_grading_budgets` before that happens.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'admin.settings.help_content.markdown',
  'admin',
  'en',
  'Help text supports Markdown. Preview shows plain text only — full rendering launches in Phase 3.',
  $$## Help content Markdown

Help text bodies accept GitHub-flavored Markdown: headings, bold, italic,
code blocks, ordered/unordered lists, and tables.

The Phase 2 admin editor shows a **plain-text preview** only. Full Markdown
rendering in the editor is deferred to Phase 3. Candidates and admins who
read the help drawer see rendered Markdown via the `HelpProvider` component.

**What to avoid:**
- Raw HTML tags — they are stripped before storage.
- Inline images — not supported in this phase.
- Custom CSS classes — the design system renders Markdown in a sandboxed
  `aiq-prose` container with fixed styles.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'candidate.intro.integrity',
  'candidate',
  'en',
  'AssessIQ measures judgment and reasoning, not memory. Use any reference you would in a real workday.',
  $$## Integrity expectations

This assessment is not a closed-book exam. AssessIQ is built to measure
how you think on the job, not what you can recall under pressure. Use:

- **Documentation** for the tools and languages you would normally
  reference at work.
- **Search engines** to look up syntax or operators.
- **Notes** you would normally have open.

Do **not** ask another person to answer for you, share screens, or paste
answers from another candidate's attempt. AssessIQ records timing
signals, edit patterns, and behavioral fingerprints; identical or
near-identical answers across candidates are flagged for review.

Once you click **Begin Assessment**, the timer starts and cannot be
paused. If your network drops, your answers are saved every 5 seconds —
you can refresh and continue.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'candidate.attempt.timer',
  'candidate',
  'en',
  'Wall-clock time remaining. Auto-submits at zero. Pausing is not supported.',
  $$## Timer

The countdown shows time remaining for the entire assessment, not the
current question. When it reaches zero, AssessIQ auto-submits whatever
answers you have entered.

**The timer keeps running even if you close the tab.** Network dropouts
do not pause it. If you genuinely cannot continue (power outage,
medical emergency), close the tab and contact your administrator
immediately — they can grant a one-time extension before submission.

Behavioral signals recorded by AssessIQ include time spent per question,
number of edits, and navigation pattern. None of these signals affect
your score directly; they inform the admin's review.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'candidate.attempt.flag',
  'candidate',
  'en',
  'Bookmark the question to revisit before final submit. Flags have no scoring impact.',
  $$## Flag for review

Use this when you want to come back to a question before final submission —
for instance, if you are not sure of your answer or want to verify a query.

Flagged questions appear with a star in the navigation panel. You can flag
multiple questions; the **Review** screen lists all flagged + unanswered
items together so you do not miss anything.

Flagging has no scoring impact. It is just a personal bookmark.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'candidate.attempt.kql.editor',
  'candidate',
  'en',
  'Write your KQL query. Syntax highlighting + autocomplete. Press Ctrl+Enter to validate.',
  $$## KQL editor

The editor offers:

- **Syntax highlighting** for KQL keywords, operators, and built-in
  functions.
- **Autocomplete** for table names referenced in the question scenario.
- **Bracket / paren matching** to spot mismatches early.
- **Format on save** (Ctrl+Shift+F) — opinionated, optional.

**Validation** (Ctrl+Enter) checks for:

- Parse errors (red underline).
- Required keyword presence — the question lists tokens that must appear
  somewhere in your query for it to score above band 0.

Validation does not run your query against real data. The grader judges
correctness by combining keyword presence with AI rubric review.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'candidate.attempt.scenario.steps',
  'candidate',
  'en',
  'Multi-step incident. Some steps may unlock only after submitting earlier steps.',
  $$## Scenario steps

Scenario questions describe a developing incident across multiple steps.
Each step asks for a decision or analysis given the evidence so far.

**Two modes:**

- **Free navigation** (default): jump between steps freely. You may
  revise earlier steps as later evidence arrives.
- **Locked progression**: each step unlocks only after you submit the
  previous one. Look for a small lock icon on later steps.

Once you submit a step in locked mode, you cannot edit it. In free mode
every step stays editable until you submit the assessment.

Behavioral note: AssessIQ records the order you visited the steps. There
is no "correct" order — exploring later evidence first is a valid
strategy.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'candidate.attempt.subjective.length',
  'candidate',
  'en',
  'Recommended 80–200 words per answer. Quality of reasoning beats word count.',
  $$## Subjective answer length

Subjective questions are graded on the rubric (anchors and bands), not on
length. A 60-word answer that nails the tradeoff scores higher than a
300-word answer that meanders.

**Rough guide:**

- **Below 40 words:** rarely enough to demonstrate reasoning.
- **80–200 words:** the sweet spot for most rubrics.
- **Above 300 words:** law of diminishing returns; you are using time
  that other questions need.

Markdown formatting (bullets, **bold**, `code`) renders in the grader's
review. Use it when it clarifies; do not use it as filler.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'candidate.attempt.disconnect',
  'candidate',
  'en',
  'Your answers autosave every 5 seconds. Refresh and continue — the timer keeps running.',
  $$## If your connection drops

AssessIQ saves your in-progress answers to the server every 5 seconds and
shows a small green check next to "Saved" when the latest save completed.
A red dot means the last save attempt failed; AssessIQ will retry on the
next interval.

**If you lose connectivity:**

1. **The timer keeps running** — wall-clock time, not connected time.
2. **Reconnect and refresh** — your most recent autosaved state loads.
3. **Anything typed during the offline window is lost** — only saved
   state survives a refresh.

For a genuinely-blocking outage (power, hardware failure), close the tab
and contact your administrator. They can grant a one-time extension
before final submission, but cannot extend after auto-submit fires.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'candidate.attempt.submit.confirm',
  'candidate',
  'en',
  'Once submitted, you cannot reopen the attempt. Verify your flagged questions first.',
  $$## Submitting your attempt

Submission is **final**. AssessIQ does not allow editing answers after
submit, and there is no second attempt unless your administrator
explicitly grants one.

Before clicking the final **Submit** button, the **Review** screen shows:

- Flagged questions you wanted to revisit.
- Unanswered questions (a blank textarea or empty MCQ counts).
- Questions whose autosave is stale (rare — usually only seconds old).

Walk through any starred or unanswered items. When you are ready, click
**Submit**. AssessIQ confirms submission with a final dialog and the
candidate timer freezes immediately.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'candidate.submit.confirm',
  'candidate',
  'en',
  'Final confirmation — clicking Submit ends the attempt and starts the grading queue.',
  $$## Final submit dialog

This dialog is the last step. Once you confirm, AssessIQ:

1. Freezes your answers and the timer.
2. Records all behavioral signals.
3. Queues the attempt for grading.
4. Emails your administrator that the attempt is ready for review.

**You will not see your score immediately.** AI grading runs synchronously
when an admin opens your attempt for review (Phase 1). Your administrator
will email you once the score is released; depending on their workflow,
that can be the same day or several days later.

There is no "save and continue later" option from this dialog — once you
are here, you have committed to submitting.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;

INSERT INTO help_content (id, tenant_id, key, audience, locale, short_text, long_md, version, status)
VALUES (
  gen_random_uuid(),
  NULL,
  'candidate.result.bands',
  'candidate',
  'en',
  'Bands 0/25/50/75/100 represent your performance vs the rubric, not a raw percentage.',
  $$## Understanding your score

AssessIQ does not report raw percentages for subjective and scenario
questions. Instead, every answer lands on a **band**:

| Band | Meaning |
|---|---|
| **0** | Missing, off-topic, or fundamentally incorrect |
| **25** | Touched the right area but missed the key point |
| **50** | Partial credit — covered some of the rubric, missed the rest |
| **75** | Substantially correct, with one notable gap |
| **100** | Complete and well-reasoned per the rubric anchors |

**Why bands and not percentages?** Subjective work is not millimetric.
Two graders comparing "73% vs 76%" learn nothing useful; comparing band
50 vs band 75 forces a clear judgement call. AssessIQ surfaces the AI's
band, the AI's justification, and any admin override side-by-side — so
your record is transparent end-to-end.

MCQ and KQL questions also map to bands so the final score has a
consistent shape.
$$,
  1,
  'active'
) ON CONFLICT (tenant_id, key, locale, version) DO NOTHING;
